import { yamlScalar } from '../files/yaml-util.ts';
import { textLayoutFromPhysical } from '../layouts/derive.ts';
import { layoutLabel, physicalLayoutNode } from '../layouts/dtsi.ts';
import { definitionPath, serializeHardware, shieldDir } from './definition.ts';
import { hardwareLayout, type KeyboardHardware, type Pin, type Side } from './types.ts';
import { directPins, halfSize, matrixPins } from './wiring.ts';

const note = (hw: KeyboardHardware) => `Generated by ZMK Editor from ${hw.name}.editor.json.`;

/** Each shield ZMK builds: `<name>_left`/`_right` on a split, else `<name>`. */
function shields(hw: KeyboardHardware): { shield: string; symbol: string }[] {
  const names = hw.split ? [`${hw.name}_left`, `${hw.name}_right`] : [hw.name];
  return names.map((shield) => ({ shield, symbol: `SHIELD_${shield.toUpperCase()}` }));
}

function kconfigShield(hw: KeyboardHardware): string {
  const entries = shields(hw).map(({ shield, symbol }) => `config ${symbol}\n    def_bool $(shields_list_contains,${shield})\n`);
  return `# ${note(hw)}\n\n${entries.join('\n')}`;
}

function kconfigDefconfig(hw: KeyboardHardware): string {
  const [first, second] = shields(hw);
  const name = `config ZMK_KEYBOARD_NAME\n    default "${hw.displayName}"\n`;
  if (!hw.split || !first || !second) return `# ${note(hw)}\n\nif ${first?.symbol ?? ''}\n\n${name}\nendif\n`;
  return `# ${note(hw)}

if ${first.symbol}

${name}
config ZMK_SPLIT_ROLE_CENTRAL
    default y

endif

if ${first.symbol} || ${second.symbol}

config ZMK_SPLIT
    default y

endif
`;
}

function zmkYml(hw: KeyboardHardware): string {
  const lines = [
    `# ${note(hw)}`,
    'file_format: "1"',
    `id: ${hw.name}`,
    `name: ${yamlScalar(hw.displayName)}`,
    'type: shield',
    'requires: [pro_micro]',
    'features:',
    '  - keys',
  ];
  if (hw.split) lines.push('siblings:', ...shields(hw).map(({ shield }) => `  - ${shield}`));
  return `${lines.join('\n')}\n`;
}

// Flags as in ZMK's own shields (v0.3): the pins the matrix reads get the pull-down.
const INPUT = '(GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)';
const OUTPUT = 'GPIO_ACTIVE_HIGH';
const DIRECT = '(GPIO_ACTIVE_LOW | GPIO_PULL_UP)';

function gpioList(property: string, pins: Pin[], flags: string, indent: string): string {
  const entries = pins.map((pin, i) => `${indent}    ${i === 0 ? '=' : ','} <&pro_micro ${String(pin ?? '?').padStart(2)} ${flags}>`);
  return [`${indent}${property}`, ...entries, `${indent}    ;`].join('\n');
}

function kscanPins(hw: KeyboardHardware, side: Side | undefined, indent: string): string {
  if (hw.wiring.kind === 'direct') return gpioList('input-gpios', directPins(hw.wiring, side), DIRECT, indent);
  const { rows, cols } = matrixPins(hw.wiring, side);
  const rowsRead = hw.wiring.diodeDirection === 'col2row';
  return [gpioList('row-gpios', rows, rowsRead ? INPUT : OUTPUT, indent), gpioList('col-gpios', cols, rowsRead ? OUTPUT : INPUT, indent)].join('\n\n');
}

function kscanNode(hw: KeyboardHardware, withPins: boolean): string {
  const lines = ['    kscan0: kscan {'];
  if (hw.wiring.kind === 'direct') lines.push('        compatible = "zmk,kscan-gpio-direct";', '        wakeup-source;');
  else lines.push('        compatible = "zmk,kscan-gpio-matrix";', '        wakeup-source;', `        diode-direction = "${hw.wiring.diodeDirection}";`);
  if (withPins) lines.push('', kscanPins(hw, undefined, '        '));
  lines.push('    };');
  return lines.join('\n');
}

/** The matrix transform, its `map` laid out like the keys. Right-half columns come after the left's. */
function transformNode(hw: KeyboardHardware): string {
  const left = halfSize(hw, hw.split ? 'left' : undefined);
  const right = hw.split ? halfSize(hw, 'right') : { rows: 0, cols: 0 };
  const cells = hw.keys.map((k) => `RC(${k.row},${k.col + (k.side === 'right' ? left.cols : 0)})`);
  const grid = textLayoutFromPhysical(hardwareLayout(hw))?.rows ?? [];
  const width = Math.max(0, ...cells.map((c) => c.length));
  const map = grid.map((row) => row.map((i) => (i === null ? '' : (cells[i] ?? ''))).map((c) => c.padEnd(width)).join(' ').trimEnd());
  return [
    '    default_transform: keymap_transform_0 {',
    '        compatible = "zmk,matrix-transform";',
    `        rows = <${Math.max(left.rows, right.rows)}>;`,
    `        columns = <${left.cols + right.cols}>;`,
    '        map = <',
    ...map,
    '        >;',
    '    };',
  ].join('\n');
}

function rootFile(hw: KeyboardHardware, withPins: boolean): string {
  return `/* ${note(hw)} */

#include <dt-bindings/zmk/matrix_transform.h>
#include <physical_layouts.dtsi>

/ {
    chosen {
        zmk,kscan = &kscan0;
        zmk,physical-layout = &${layoutLabel(hw.name)};
    };

${kscanNode(hw, withPins)}

${transformNode(hw)}

${physicalLayoutNode(hardwareLayout(hw), hw.name, hw.displayName, ['transform = <&default_transform>;'])}
};
`;
}

function halfOverlay(hw: KeyboardHardware, side: Side): string {
  const parts = [`/* ${note(hw)} */`, `#include "${hw.name}.dtsi"`];
  if (side === 'right') parts.push(`&default_transform {\n    col-offset = <${halfSize(hw, 'left').cols}>;\n};`);
  parts.push(`&kscan0 {\n${kscanPins(hw, side, '    ')}\n};`);
  return `${parts.join('\n\n')}\n`;
}

/** Every file of the keyboard's shield, keyed by repo path. */
export function generateShield(hw: KeyboardHardware): Record<string, string> {
  const dir = shieldDir(hw.name);
  const files: Record<string, string> = {
    [`${dir}/Kconfig.shield`]: kconfigShield(hw),
    [`${dir}/Kconfig.defconfig`]: kconfigDefconfig(hw),
    [`${dir}/${hw.name}.zmk.yml`]: zmkYml(hw),
    [definitionPath(hw.name)]: serializeHardware(hw),
  };
  if (hw.split) {
    files[`${dir}/${hw.name}.dtsi`] = rootFile(hw, false);
    files[`${dir}/${hw.name}_left.overlay`] = halfOverlay(hw, 'left');
    files[`${dir}/${hw.name}_right.overlay`] = halfOverlay(hw, 'right');
  } else {
    files[`${dir}/${hw.name}.overlay`] = rootFile(hw, true);
  }
  return files;
}
