import { yamlScalar } from '../files/yaml-util.ts';
import { definitionPath, serializeHardware, shieldDir } from './definition.ts';
import type { KeyboardHardware } from './types.ts';

const note = (hw: KeyboardHardware) => `Generated by ZMK Editor from ${hw.name}.editor.json.`;

/** Each shield ZMK builds: `<name>_left`/`_right` on a split, else `<name>`. */
function shields(hw: KeyboardHardware): { shield: string; symbol: string }[] {
  const names = hw.split ? [`${hw.name}_left`, `${hw.name}_right`] : [hw.name];
  return names.map((shield) => ({ shield, symbol: `SHIELD_${shield.toUpperCase()}` }));
}

function kconfigShield(hw: KeyboardHardware): string {
  const entries = shields(hw).map(({ shield, symbol }) => `config ${symbol}\n    def_bool $(shields_list_contains,${shield})\n`);
  return `# ${note(hw)}\n\n${entries.join('\n')}`;
}

function kconfigDefconfig(hw: KeyboardHardware): string {
  const [first, second] = shields(hw);
  const name = `config ZMK_KEYBOARD_NAME\n    default "${hw.displayName}"\n`;
  if (!hw.split || !first || !second) return `# ${note(hw)}\n\nif ${first?.symbol ?? ''}\n\n${name}\nendif\n`;
  return `# ${note(hw)}

if ${first.symbol}

${name}
config ZMK_SPLIT_ROLE_CENTRAL
    default y

endif

if ${first.symbol} || ${second.symbol}

config ZMK_SPLIT
    default y

endif
`;
}

function zmkYml(hw: KeyboardHardware): string {
  const lines = [
    `# ${note(hw)}`,
    'file_format: "1"',
    `id: ${hw.name}`,
    `name: ${yamlScalar(hw.displayName)}`,
    'type: shield',
    'requires: [pro_micro]',
    'features:',
    '  - keys',
  ];
  if (hw.split) lines.push('siblings:', ...shields(hw).map(({ shield }) => `  - ${shield}`));
  return `${lines.join('\n')}\n`;
}

/** Every file of the keyboard's shield, keyed by repo path. */
export function generateShield(hw: KeyboardHardware): Record<string, string> {
  const dir = shieldDir(hw.name);
  return {
    [`${dir}/Kconfig.shield`]: kconfigShield(hw),
    [`${dir}/Kconfig.defconfig`]: kconfigDefconfig(hw),
    [`${dir}/${hw.name}.zmk.yml`]: zmkYml(hw),
    [definitionPath(hw.name)]: serializeHardware(hw),
  };
}
