import { describe, expect, it } from 'vitest';
import { generateShield } from './generate.ts';
import { testPad, testSplit } from './testFixtures.ts';

const dir = (name: string) => `config/boards/shields/${name}`;

describe('generateShield: Kconfig and metadata', () => {
  it('writes the split Kconfig files like ZMK’s own split shields', () => {
    const files = generateShield(testSplit);
    expect(files[`${dir('test_split')}/Kconfig.shield`]).toBe(`# Generated by ZMK Editor from test_split.editor.json.

config SHIELD_TEST_SPLIT_LEFT
    def_bool $(shields_list_contains,test_split_left)

config SHIELD_TEST_SPLIT_RIGHT
    def_bool $(shields_list_contains,test_split_right)
`);
    expect(files[`${dir('test_split')}/Kconfig.defconfig`]).toBe(`# Generated by ZMK Editor from test_split.editor.json.

if SHIELD_TEST_SPLIT_LEFT

config ZMK_KEYBOARD_NAME
    default "Test Split"

config ZMK_SPLIT_ROLE_CENTRAL
    default y

endif

if SHIELD_TEST_SPLIT_LEFT || SHIELD_TEST_SPLIT_RIGHT

config ZMK_SPLIT
    default y

endif
`);
    expect(files[`${dir('test_split')}/test_split.zmk.yml`]).toBe(`# Generated by ZMK Editor from test_split.editor.json.
file_format: "1"
id: test_split
name: Test Split
type: shield
requires: [pro_micro]
features:
  - keys
siblings:
  - test_split_left
  - test_split_right
`);
  });

  it('writes a unibody keyboard as a single shield', () => {
    const files = generateShield(testPad);
    expect(files[`${dir('test_pad')}/Kconfig.shield`]).toBe(`# Generated by ZMK Editor from test_pad.editor.json.

config SHIELD_TEST_PAD
    def_bool $(shields_list_contains,test_pad)
`);
    expect(files[`${dir('test_pad')}/Kconfig.defconfig`]).toBe(`# Generated by ZMK Editor from test_pad.editor.json.

if SHIELD_TEST_PAD

config ZMK_KEYBOARD_NAME
    default "Test Pad"

endif
`);
    expect(files[`${dir('test_pad')}/test_pad.zmk.yml`]).not.toContain('siblings');
    expect(files[`${dir('test_pad')}/test_pad.editor.json`]).toContain('"name": "test_pad"');
  });
});
