import { yamlScalar } from '../files/yaml-util.ts';
import { textLayoutFromPhysical } from '../layouts/derive.ts';
import { layoutLabel, physicalLayoutNode } from '../layouts/dtsi.ts';
import { normalizedLayout } from '../layouts/normalize.ts';
import { definitionPath, parseHardware, serializeHardware, shieldDir } from './definition.ts';
import { halfDisplay, halfDisplayPins, usesNiceViewAdapter, type DisplayPin } from './displays.ts';
import { interconnectOf, nrfPin } from './interconnects.ts';
import { sensorLabel, sensorOrder } from './encoders.ts';
import { isShiftOutput, outputCount, sharesNiceViewBus, shiftPins } from './shiftRegisters.ts';
import { hardwareLayout, type DisplayKind, type DisplaySignal, type KeyboardHardware, type LinePin, type Pin, type Side } from './types.ts';
import { directPins, halfSize, matrixPins } from './wiring.ts';

const note = (hw: KeyboardHardware) => `Generated by ZMK Editor from ${hw.name}.editor.json.`;

/** Each shield ZMK builds: `<name>_left`/`_right` on a split, else `<name>`. */
function shields(hw: KeyboardHardware): { shield: string; symbol: string }[] {
  const names = hw.split ? [`${hw.name}_left`, `${hw.name}_right`] : [hw.name];
  return names.map((shield) => ({ shield, symbol: `SHIELD_${shield.toUpperCase()}` }));
}

function kconfigShield(hw: KeyboardHardware): string {
  const entries = shields(hw).map(({ shield, symbol }) => `config ${symbol}\n    def_bool $(shields_list_contains,${shield})\n`);
  return `# ${note(hw)}\n\n${entries.join('\n')}`;
}

// As in ZMK's Sofle (v0.3).
const ENCODER_FLAGS = '(GPIO_ACTIVE_HIGH | GPIO_PULL_UP)';

const EC11_TRIGGER = `choice EC11_TRIGGER_MODE
    default EC11_TRIGGER_GLOBAL_THREAD
endchoice
`;

/** The encoder nodes and the sensors node, or '' without encoders. On splits every encoder starts disabled. */
function encoderNodes(hw: KeyboardHardware): string {
  const sensors = sensorOrder(hw);
  if (sensors.length === 0) return '';
  const { gpio } = interconnectOf(hw.controller);
  const pin = (p: Pin) => String(p ?? '?').padStart(2);
  const nodes = sensors.map(({ side, index, encoder }) =>
    [
      `    ${sensorLabel(side, index)}: ${side ? `encoder_${side}_${index}` : `encoder_${index}`} {`,
      '        compatible = "alps,ec11";',
      `        a-gpios = <&${gpio} ${pin(encoder.a)} ${ENCODER_FLAGS}>;`,
      `        b-gpios = <&${gpio} ${pin(encoder.b)} ${ENCODER_FLAGS}>;`,
      '        steps = <80>;',
      ...(hw.split ? ['        status = "disabled";'] : []),
      '    };',
    ].join('\n'),
  );
  const sensorsNode = [
    '    sensors: sensors {',
    '        compatible = "zmk,keymap-sensors";',
    `        sensors = <${sensors.map(({ side, index }) => `&${sensorLabel(side, index)}`).join(' ')}>;`,
    '        triggers-per-rotation = <20>;',
    '    };',
  ].join('\n');
  return [...nodes, sensorsNode].join('\n\n');
}

/** `&pinctrl` default and sleep states for a display bus, as in ZMK's nice_view_adapter overlays. */
function pinctrlNodes(label: string, psels: string[]): string {
  const state = (name: string, sleep: boolean) => [
    `    ${name}: ${name} {`,
    '        group1 {',
    `            psels = ${psels.join(',\n                ')};`,
    ...(sleep ? ['            low-power-enable;'] : []),
    '        };',
    '    };',
  ];
  return ['&pinctrl {', ...state(`${label}_default`, false), ...state(`${label}_sleep`, true), '};'].join('\n');
}

/** `<NRF_PSEL(SPIM_SCK, 0, 20)>` for a controller's D-pin; `?` where it has none (validation stops that). */
function psel(name: string, controller: string, pin: Pin): string {
  const nrf = pin === null ? undefined : nrfPin(controller, pin);
  return `<NRF_PSEL(${name}, ${nrf ? `${nrf.port}, ${nrf.pin}` : '?, ?'})>`;
}

const signalPin = (pins: DisplayPin[], signal: DisplaySignal): Pin => pins.find((p) => p.signal === signal)?.pin ?? null;

/**
 * A nice!view's own SPI bus, for one ZMK's adapter doesn't cover: the same
 * nodes the adapter's board overlays define, on the chosen pins. The display
 * sends nothing back, so there is no MISO.
 */
function niceViewBus(hw: KeyboardHardware, pins: DisplayPin[]): string {
  const ic = interconnectOf(hw.controller);
  const cs = signalPin(pins, 'cs');
  // Shift registers sharing the bus are its second device, selected by their latch (active low).
  const shared = sharesNiceViewBus(hw);
  const latch = hw.shiftRegisters?.latch ?? null;
  const csGpios = shared
    ? `    cs-gpios = <&${ic.gpio} ${cs ?? '?'} GPIO_ACTIVE_HIGH>, <&${ic.gpio} ${latch ?? '?'} GPIO_ACTIVE_LOW>;`
    : `    cs-gpios = <&${ic.gpio} ${cs ?? '?'} GPIO_ACTIVE_HIGH>;`;
  return [
    pinctrlNodes('nice_view_spi', [psel('SPIM_SCK', hw.controller, signalPin(pins, 'clock')), psel('SPIM_MOSI', hw.controller, signalPin(pins, 'data'))]),
    '',
    `nice_view_spi: &${ic.spi} {`,
    ...(shared ? ['    status = "okay";'] : []),
    '    compatible = "nordic,nrf-spim";',
    '    pinctrl-0 = <&nice_view_spi_default>;',
    '    pinctrl-1 = <&nice_view_spi_sleep>;',
    '    pinctrl-names = "default", "sleep";',
    csGpios,
    ...(shared ? ['', ...shifterNode(1, outputCount(hw))] : []),
    '};',
    '',
    // As the adapter does: on some Pro Micro boards the SPI bus is SPI0, which shares its hardware with I2C0.
    `&${ic.i2c} {`,
    '    status = "disabled";',
    '};',
  ].join('\n');
}

/** The 74HC595 chain as an SPI device (ZMK's `zmk,gpio-595`). */
function shifterNode(reg: number, outputs: number): string[] {
  return [
    `    shifter: 595@${reg} {`,
    '        compatible = "zmk,gpio-595";',
    '        status = "okay";',
    '        gpio-controller;',
    '        spi-max-frequency = <1000000>;',
    `        reg = <${reg}>;`,
    '        #gpio-cells = <2>;',
    `        ngpios = <${outputs}>;`,
    '    };',
  ];
}

/**
 * Shift registers on their own bus: SPI2, which shares hardware with no I2C
 * unit (so an OLED keeps working) and that no supported board uses otherwise.
 * The latch (RCLK) is the chip select; the 595 sends nothing back, so there's no MISO.
 */
function shiftRegisterBus(hw: KeyboardHardware): string | undefined {
  const pins = shiftPins(hw);
  if (!pins || pins.shared) return undefined;
  const { gpio } = interconnectOf(hw.controller);
  return [
    pinctrlNodes('shift_register_spi', [psel('SPIM_SCK', hw.controller, pins.clock), psel('SPIM_MOSI', hw.controller, pins.data)]),
    '',
    '&spi2 {',
    '    status = "okay";',
    '    compatible = "nordic,nrf-spim";',
    '    pinctrl-0 = <&shift_register_spi_default>;',
    '    pinctrl-1 = <&shift_register_spi_sleep>;',
    '    pinctrl-names = "default", "sleep";',
    `    cs-gpios = <&${gpio} ${pins.latch ?? '?'} GPIO_ACTIVE_LOW>;`,
    '',
    ...shifterNode(0, outputCount(hw)),
    '};',
  ].join('\n');
}

/** A half's display nodes: an OLED (its bus moved to the chosen pins), or a nice!view's own SPI bus; none otherwise. */
function displayNodes(hw: KeyboardHardware, side?: Side): string | undefined {
  const kind = halfDisplay(hw, side);
  const pins = halfDisplayPins(hw, side);
  if (isOled(kind)) {
    const ic = interconnectOf(hw.controller);
    const sda = signalPin(pins, 'sda');
    const scl = signalPin(pins, 'scl');
    const moved = sda !== ic.i2cPins.sda || scl !== ic.i2cPins.scl;
    return oledNodes(kind, ic.i2c, moved ? pinctrlNodes('oled_i2c', [psel('TWIM_SDA', hw.controller, sda), psel('TWIM_SCL', hw.controller, scl)]) : undefined);
  }
  return kind === 'nice_view' && !usesNiceViewAdapter(hw, side) ? niceViewBus(hw, pins) : undefined;
}

/**
 * OLED nodes as in ZMK's Corne (128×32) and Kyria (128×64), on the controller's
 * I2C bus, plus the chosen display. `pinctrl` moves the bus off its default pins.
 */
function oledNodes(kind: DisplayKind, i2c: string, pinctrl?: string): string {
  const size =
    kind === 'oled_128x32'
      ? ['        width = <128>;', '        height = <32>;', '        segment-offset = <0>;', '        page-offset = <0>;', '        display-offset = <0>;', '        multiplex-ratio = <31>;', '        segment-remap;', '        com-invdir;', '        com-sequential;', '        inversion-on;', '        prechargep = <0x22>;']
      : ['        width = <128>;', '        height = <64>;', '        segment-offset = <0>;', '        page-offset = <0>;', '        display-offset = <0>;', '        multiplex-ratio = <63>;', '        prechargep = <0x22>;', '        inversion-on;'];
  return [
    ...(pinctrl ? [pinctrl, ''] : []),
    `&${i2c} {`,
    '    status = "okay";',
    ...(pinctrl
      ? ['    pinctrl-0 = <&oled_i2c_default>;', '    pinctrl-1 = <&oled_i2c_sleep>;', '    pinctrl-names = "default", "sleep";']
      : []),
    '',
    '    oled: ssd1306@3c {',
    '        compatible = "solomon,ssd1306fb";',
    '        reg = <0x3c>;',
    ...size,
    '    };',
    '};',
    '',
    '/ {',
    '    chosen {',
    '        zephyr,display = &oled;',
    '    };',
    '};',
  ].join('\n');
}

const isOled = (kind: DisplayKind | undefined): kind is DisplayKind => kind === 'oled_128x32' || kind === 'oled_128x64';

/** The shields (with their half) whose half has an OLED. */
function oledShields(hw: KeyboardHardware): { shield: string; symbol: string }[] {
  const all = shields(hw);
  const sides: (Side | undefined)[] = hw.split ? ['left', 'right'] : [undefined];
  return all.filter((_, i) => isOled(halfDisplay(hw, sides[i])));
}

// Display settings as in ZMK's Corne and Kyria Kconfig.defconfig (identical in both).
const DISPLAY_KCONFIG = `if ZMK_DISPLAY

config I2C
    default y

config SSD1306
    default y

endif # ZMK_DISPLAY

if LVGL

config LV_Z_VDB_SIZE
    default 64

config LV_DPI_DEF
    default 148

config LV_Z_BITS_PER_PIXEL
    default 1

choice LV_COLOR_DEPTH
    default LV_COLOR_DEPTH_1
endchoice

endif # LVGL
`;

function kconfigDefconfig(hw: KeyboardHardware): string {
  const [first, second] = shields(hw);
  const name = `config ZMK_KEYBOARD_NAME\n    default "${hw.displayName}"\n`;
  const trigger = sensorOrder(hw).length > 0 ? `\n${EC11_TRIGGER}` : '';
  const oled = oledShields(hw);
  const display = oled.length > 0 ? `\nif ${oled.map((s) => s.symbol).join(' || ')}\n\n${DISPLAY_KCONFIG}\nendif\n` : '';
  const spi = hw.shiftRegisters ? '\nconfig SPI\n    default y\n' : '';
  if (!hw.split || !first || !second) return `# ${note(hw)}\n\nif ${first?.symbol ?? ''}\n\n${name}${trigger}${spi}\nendif\n${display}`;
  return `# ${note(hw)}

if ${first.symbol}

${name}
config ZMK_SPLIT_ROLE_CENTRAL
    default y

endif

if ${first.symbol} || ${second.symbol}

config ZMK_SPLIT
    default y
${trigger}
endif
${display}`;
}

function zmkYml(hw: KeyboardHardware): string {
  const lines = [
    `# ${note(hw)}`,
    'file_format: "1"',
    `id: ${hw.name}`,
    `name: ${yamlScalar(hw.displayName)}`,
    'type: shield',
    `requires: [${interconnectOf(hw.controller).id}]`,
    'features:',
    '  - keys',
  ];
  if (hw.split) lines.push('siblings:', ...shields(hw).map(({ shield }) => `  - ${shield}`));
  return `${lines.join('\n')}\n`;
}

// Flags as in ZMK's own shields (v0.3): the pins the matrix reads get the pull-down.
const INPUT = '(GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)';
const OUTPUT = 'GPIO_ACTIVE_HIGH';
const DIRECT = '(GPIO_ACTIVE_LOW | GPIO_PULL_UP)';

function gpioList(gpio: string, property: string, pins: LinePin[], flags: string, indent: string): string {
  const ref = (pin: LinePin) => (isShiftOutput(pin) ? `&shifter ${String(pin.sr).padStart(2)}` : `&${gpio} ${String(pin ?? '?').padStart(2)}`);
  const entries = pins.map((pin, i) => `${indent}    ${i === 0 ? '=' : ','} <${ref(pin)} ${flags}>`);
  return [`${indent}${property}`, ...entries, `${indent}    ;`].join('\n');
}

function kscanPins(hw: KeyboardHardware, side: Side | undefined, indent: string): string {
  const { gpio } = interconnectOf(hw.controller);
  if (hw.wiring.kind === 'direct') return gpioList(gpio, 'input-gpios', directPins(hw.wiring, side), DIRECT, indent);
  const { rows, cols } = matrixPins(hw.wiring, side);
  const rowsRead = hw.wiring.diodeDirection === 'col2row';
  return [gpioList(gpio, 'row-gpios', rows, rowsRead ? INPUT : OUTPUT, indent), gpioList(gpio, 'col-gpios', cols, rowsRead ? OUTPUT : INPUT, indent)].join('\n\n');
}

function kscanNode(hw: KeyboardHardware, withPins: boolean): string {
  const lines = ['    kscan0: kscan {'];
  if (hw.wiring.kind === 'direct') lines.push('        compatible = "zmk,kscan-gpio-direct";', '        wakeup-source;');
  else lines.push('        compatible = "zmk,kscan-gpio-matrix";', '        wakeup-source;', `        diode-direction = "${hw.wiring.diodeDirection}";`);
  if (withPins) lines.push('', kscanPins(hw, undefined, '        '));
  lines.push('    };');
  return lines.join('\n');
}

/** The matrix transform, its `map` laid out like the keys. Right-half columns come after the left's. */
function transformNode(hw: KeyboardHardware): string {
  const left = halfSize(hw, hw.split ? 'left' : undefined);
  const right = hw.split ? halfSize(hw, 'right') : { rows: 0, cols: 0 };
  const cells = hw.keys.map((k) => `RC(${k.row},${k.col + (k.side === 'right' ? left.cols : 0)})`);
  const grid = textLayoutFromPhysical(hardwareLayout(hw))?.rows ?? [];
  const width = Math.max(0, ...cells.map((c) => c.length));
  const map = grid.map((row) => row.map((i) => (i === null ? '' : (cells[i] ?? ''))).map((c) => c.padEnd(width)).join(' ').trimEnd());
  return [
    '    default_transform: keymap_transform_0 {',
    '        compatible = "zmk,matrix-transform";',
    `        rows = <${Math.max(left.rows, right.rows)}>;`,
    `        columns = <${left.cols + right.cols}>;`,
    '        map = <',
    ...map,
    '        >;',
    '    };',
  ].join('\n');
}

/** A one-piece keyboard's display nodes and shift register bus, appended after the root block of its overlay. */
function displaySection(hw: KeyboardHardware, withPins: boolean): string {
  if (!withPins) return '';
  const parts = [displayNodes(hw), shiftRegisterBus(hw)].filter((p): p is string => p !== undefined);
  return parts.map((p) => `\n${p}\n`).join('');
}

function rootFile(hw: KeyboardHardware, withPins: boolean): string {
  return `/* ${note(hw)} */

#include <dt-bindings/zmk/matrix_transform.h>
#include <physical_layouts.dtsi>

/ {
    chosen {
        zmk,kscan = &kscan0;
        zmk,physical-layout = &${layoutLabel(hw.name)};
    };

${kscanNode(hw, withPins)}

${transformNode(hw)}

${encoderNodes(hw) ? `${encoderNodes(hw)}\n\n` : ''}${physicalLayoutNode(normalizedLayout(hardwareLayout(hw)), hw.name, hw.displayName, ['transform = <&default_transform>;'])}
};
${displaySection(hw, withPins)}`;
}

function halfOverlay(hw: KeyboardHardware, side: Side): string {
  const parts = [`/* ${note(hw)} */`, `#include "${hw.name}.dtsi"`];
  if (side === 'right') parts.push(`&default_transform {\n    col-offset = <${halfSize(hw, 'left').cols}>;\n};`);
  for (const { index } of sensorOrder(hw).filter((s) => s.side === side)) {
    parts.push(`&${sensorLabel(side, index)} {\n    status = "okay";\n};`);
  }
  parts.push(`&kscan0 {\n${kscanPins(hw, side, '    ')}\n};`);
  const display = displayNodes(hw, side);
  if (display) parts.push(display);
  return `${parts.join('\n\n')}\n`;
}

/** Every file of the keyboard's shield, keyed by repo path. */
export function generateShield(hw: KeyboardHardware): Record<string, string> {
  const dir = shieldDir(hw.name);
  const files: Record<string, string> = {
    [`${dir}/Kconfig.shield`]: kconfigShield(hw),
    [`${dir}/Kconfig.defconfig`]: kconfigDefconfig(hw),
    [`${dir}/${hw.name}.zmk.yml`]: zmkYml(hw),
    [definitionPath(hw.name)]: serializeHardware(hw),
  };
  if (hw.split) {
    files[`${dir}/${hw.name}.dtsi`] = rootFile(hw, false);
    files[`${dir}/${hw.name}_left.overlay`] = halfOverlay(hw, 'left');
    files[`${dir}/${hw.name}_right.overlay`] = halfOverlay(hw, 'right');
  } else {
    files[`${dir}/${hw.name}.overlay`] = rootFile(hw, true);
  }
  for (const { shield } of oledShields(hw)) files[`${dir}/${shield}.conf`] = `# ${note(hw)}\nCONFIG_ZMK_DISPLAY=y\n`;
  return files;
}

/**
 * Shield files in a repo that differ from what the repo's own definition
 * generates, i.e. edited by hand. Missing files don't count.
 */
export function handEditedShieldFiles(files: Record<string, string>, keyboard: string): string[] {
  return Object.entries(previouslyGenerated(files, keyboard))
    .filter(([path, generated]) => {
      const existing = files[path];
      return existing !== undefined && !sameText(existing, generated);
    })
    .map(([path]) => path);
}

/**
 * Shield files the repo's own definition generated that `generated` no longer
 * has (e.g. a removed display's .conf), left untouched since: they should be
 * deleted on commit. Hand-edited ones stay.
 */
export function staleShieldFiles(files: Record<string, string>, keyboard: string, generated: Record<string, string>): string[] {
  return Object.entries(previouslyGenerated(files, keyboard))
    .filter(([path, before]) => {
      const existing = files[path];
      return !(path in generated) && existing !== undefined && sameText(existing, before);
    })
    .map(([path]) => path);
}

const sameText = (a: string, b: string) => a.replace(/\r\n/g, '\n') === b;

/** What the repo's own definition generates; empty without a readable one. */
function previouslyGenerated(files: Record<string, string>, keyboard: string): Record<string, string> {
  const text = files[definitionPath(keyboard)];
  if (text === undefined) return {};
  try {
    return generateShield(parseHardware(text));
  } catch {
    return {};
  }
}
