import { describe, expect, it } from 'vitest';
import { hardwareBuildTargets } from './config.ts';
import { setDisplay, setDisplayPin } from './displays.ts';
import { generateShield, staleShieldFiles } from './generate.ts';
import { setShiftOwnBus, setShiftPin } from './shiftRegisters.ts';
import { testPad, testShiftPad, testSplit } from './testFixtures.ts';
import type { KeyboardHardware } from './types.ts';

const dir = (name: string) => `config/boards/shields/${name}`;

describe('generateShield: Kconfig and metadata', () => {
  it('writes the split Kconfig files like ZMK’s own split shields', () => {
    const files = generateShield(testSplit);
    expect(files[`${dir('test_split')}/Kconfig.shield`]).toBe(`# Generated by ZMK Editor from test_split.editor.json.

config SHIELD_TEST_SPLIT_LEFT
    def_bool $(shields_list_contains,test_split_left)

config SHIELD_TEST_SPLIT_RIGHT
    def_bool $(shields_list_contains,test_split_right)
`);
    expect(files[`${dir('test_split')}/Kconfig.defconfig`]).toBe(`# Generated by ZMK Editor from test_split.editor.json.

if SHIELD_TEST_SPLIT_LEFT

config ZMK_KEYBOARD_NAME
    default "Test Split"

config ZMK_SPLIT_ROLE_CENTRAL
    default y

endif

if SHIELD_TEST_SPLIT_LEFT || SHIELD_TEST_SPLIT_RIGHT

config ZMK_SPLIT
    default y

endif
`);
    expect(files[`${dir('test_split')}/test_split.zmk.yml`]).toBe(`# Generated by ZMK Editor from test_split.editor.json.
file_format: "1"
id: test_split
name: Test Split
type: shield
requires: [pro_micro]
features:
  - keys
siblings:
  - test_split_left
  - test_split_right
`);
  });

  it('writes a unibody keyboard as a single shield', () => {
    const files = generateShield(testPad);
    expect(files[`${dir('test_pad')}/Kconfig.shield`]).toBe(`# Generated by ZMK Editor from test_pad.editor.json.

config SHIELD_TEST_PAD
    def_bool $(shields_list_contains,test_pad)
`);
    expect(files[`${dir('test_pad')}/Kconfig.defconfig`]).toBe(`# Generated by ZMK Editor from test_pad.editor.json.

if SHIELD_TEST_PAD

config ZMK_KEYBOARD_NAME
    default "Test Pad"

endif
`);
    expect(files[`${dir('test_pad')}/test_pad.zmk.yml`]).not.toContain('siblings');
    expect(files[`${dir('test_pad')}/test_pad.editor.json`]).toContain('"name": "test_pad"');
  });
});

describe('generateShield: devicetree', () => {
  it('writes a unibody direct-wired keyboard as one overlay', () => {
    expect(generateShield(testPad)[`${dir('test_pad')}/test_pad.overlay`]).toBe(`/* Generated by ZMK Editor from test_pad.editor.json. */

#include <dt-bindings/zmk/matrix_transform.h>
#include <physical_layouts.dtsi>

/ {
    chosen {
        zmk,kscan = &kscan0;
        zmk,physical-layout = &test_pad_layout;
    };

    kscan0: kscan {
        compatible = "zmk,kscan-gpio-direct";
        wakeup-source;

        input-gpios
            = <&pro_micro  4 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>
            , <&pro_micro  5 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>
            ;
    };

    default_transform: keymap_transform_0 {
        compatible = "zmk,matrix-transform";
        rows = <1>;
        columns = <2>;
        map = <
RC(0,0) RC(0,1)
        >;
    };

    test_pad_layout: test_pad_layout {
        compatible = "zmk,physical-layout";
        display-name = "Test Pad";
        transform = <&default_transform>;

        keys  //                     w   h    x    y     rot   rx   ry
            = <&key_physical_attrs 100 100    0    0      0    0    0>
            , <&key_physical_attrs 100 100  100    0      0    0    0>
            ;
    };
};
`);
  });

  it('writes a split as a shared .dtsi and one overlay per half, the right one mirrored and offset', () => {
    const files = generateShield(testSplit);
    expect(Object.keys(files).sort()).toEqual([
      `${dir('test_split')}/Kconfig.defconfig`,
      `${dir('test_split')}/Kconfig.shield`,
      `${dir('test_split')}/test_split.dtsi`,
      `${dir('test_split')}/test_split.editor.json`,
      `${dir('test_split')}/test_split.zmk.yml`,
      `${dir('test_split')}/test_split_left.overlay`,
      `${dir('test_split')}/test_split_right.overlay`,
    ]);
    const dtsi = files[`${dir('test_split')}/test_split.dtsi`] ?? '';
    expect(dtsi).toContain(`    kscan0: kscan {
        compatible = "zmk,kscan-gpio-matrix";
        wakeup-source;
        diode-direction = "col2row";
    };`);
    expect(dtsi).toContain(`        rows = <1>;
        columns = <4>;
        map = <
RC(0,0) RC(0,1) RC(0,2) RC(0,3)
        >;`);
    expect(files[`${dir('test_split')}/test_split_left.overlay`]).toBe(`/* Generated by ZMK Editor from test_split.editor.json. */

#include "test_split.dtsi"

&kscan0 {
    row-gpios
        = <&pro_micro  4 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
        ;

    col-gpios
        = <&pro_micro  6 GPIO_ACTIVE_HIGH>
        , <&pro_micro  7 GPIO_ACTIVE_HIGH>
        ;
};
`);
    expect(files[`${dir('test_split')}/test_split_right.overlay`]).toBe(`/* Generated by ZMK Editor from test_split.editor.json. */

#include "test_split.dtsi"

&default_transform {
    col-offset = <2>;
};

&kscan0 {
    row-gpios
        = <&pro_micro  4 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
        ;

    col-gpios
        = <&pro_micro  7 GPIO_ACTIVE_HIGH>
        , <&pro_micro  6 GPIO_ACTIVE_HIGH>
        ;
};
`);
  });

  it('normalizes negative and fractional layout values so dtc accepts them', () => {
    const [key0, key1] = testPad.keys;
    if (!key0 || !key1) throw new Error('testPad needs at least two keys');
    const hw: KeyboardHardware = {
      ...testPad,
      keys: [
        { ...key0, x: -25, y: 0 },
        { ...key1, x: 100, y: 0, w: 125, r: 15, rx: 100 + 125 / 2, ry: 50 },
      ],
    };
    const overlay = generateShield(hw)[`${dir('test_pad')}/test_pad.overlay`] ?? '';
    const attrLines = overlay.split('\n').filter((line) => line.includes('key_physical_attrs'));
    expect(attrLines.length).toBeGreaterThan(0);
    for (const line of attrLines) {
      expect(line.replace(/\([^)]*\)/g, '')).not.toContain('-');
      expect(line).not.toContain('.');
    }
  });

  it('puts the pull-down on the columns for row2col diodes', () => {
    const rowToCol: KeyboardHardware = { ...testSplit, wiring: { kind: 'matrix', diodeDirection: 'row2col', rows: [4], cols: [6, 7] } };
    const left = generateShield(rowToCol)[`${dir('test_split')}/test_split_left.overlay`];
    expect(left).toContain('row-gpios\n        = <&pro_micro  4 GPIO_ACTIVE_HIGH>');
    expect(left).toContain('col-gpios\n        = <&pro_micro  6 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>');
  });
});

describe('generateShield: encoders', () => {
  const padWithEncoder: KeyboardHardware = { ...testPad, encoders: [{ a: 8, b: 9 }] };
  const splitWithEncoders: KeyboardHardware = { ...testSplit, encoders: [{ a: 8, b: 9 }] };

  it('defines a one-piece keyboard’s encoder and the sensors node, and picks the EC11 trigger', () => {
    const files = generateShield(padWithEncoder);
    const overlay = files[`${dir('test_pad')}/test_pad.overlay`] ?? '';
    expect(overlay).toContain(`    encoder_0: encoder_0 {
        compatible = "alps,ec11";
        a-gpios = <&pro_micro  8 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>;
        b-gpios = <&pro_micro  9 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>;
        steps = <80>;
    };

    sensors: sensors {
        compatible = "zmk,keymap-sensors";
        sensors = <&encoder_0>;
        triggers-per-rotation = <20>;
    };`);
    expect(files[`${dir('test_pad')}/Kconfig.defconfig`]).toBe(`# Generated by ZMK Editor from test_pad.editor.json.

if SHIELD_TEST_PAD

config ZMK_KEYBOARD_NAME
    default "Test Pad"

choice EC11_TRIGGER_MODE
    default EC11_TRIGGER_GLOBAL_THREAD
endchoice

endif
`);
  });

  it('puts a split’s encoders in the .dtsi, disabled, and enables each half’s own (right pins mirrored)', () => {
    const files = generateShield(splitWithEncoders);
    const dtsi = files[`${dir('test_split')}/test_split.dtsi`] ?? '';
    expect(dtsi).toContain(`    left_encoder_0: encoder_left_0 {
        compatible = "alps,ec11";
        a-gpios = <&pro_micro  8 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>;
        b-gpios = <&pro_micro  9 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>;
        steps = <80>;
        status = "disabled";
    };

    right_encoder_0: encoder_right_0 {
        compatible = "alps,ec11";
        a-gpios = <&pro_micro  9 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>;
        b-gpios = <&pro_micro  8 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>;
        steps = <80>;
        status = "disabled";
    };

    sensors: sensors {
        compatible = "zmk,keymap-sensors";
        sensors = <&left_encoder_0 &right_encoder_0>;
        triggers-per-rotation = <20>;
    };`);
    expect(files[`${dir('test_split')}/test_split_left.overlay`]).toContain('&left_encoder_0 {\n    status = "okay";\n};');
    expect(files[`${dir('test_split')}/test_split_left.overlay`]).not.toContain('right_encoder_0');
    expect(files[`${dir('test_split')}/test_split_right.overlay`]).toContain('&right_encoder_0 {\n    status = "okay";\n};');
    expect(files[`${dir('test_split')}/Kconfig.defconfig`]).toContain(`config ZMK_SPLIT
    default y

choice EC11_TRIGGER_MODE
    default EC11_TRIGGER_GLOBAL_THREAD
endchoice

endif
`);
  });

  it('changes nothing for keyboards without encoders', () => {
    expect(generateShield({ ...testSplit, encoders: [] })).toEqual(generateShield(testSplit));
  });
});

describe('generateShield: displays', () => {
  const oledNode32 = `&pro_micro_i2c {
    status = "okay";

    oled: ssd1306@3c {
        compatible = "solomon,ssd1306fb";
        reg = <0x3c>;
        width = <128>;
        height = <32>;
        segment-offset = <0>;
        page-offset = <0>;
        display-offset = <0>;
        multiplex-ratio = <31>;
        segment-remap;
        com-invdir;
        com-sequential;
        inversion-on;
        prechargep = <0x22>;
    };
};

/ {
    chosen {
        zephyr,display = &oled;
    };
};`;

  const displayKconfig = (condition: string) => `if ${condition}

if ZMK_DISPLAY

config I2C
    default y

config SSD1306
    default y

endif # ZMK_DISPLAY

if LVGL

config LV_Z_VDB_SIZE
    default 64

config LV_DPI_DEF
    default 148

config LV_Z_BITS_PER_PIXEL
    default 1

choice LV_COLOR_DEPTH
    default LV_COLOR_DEPTH_1
endchoice

endif # LVGL

endif
`;

  it('puts a left-only 128×32 OLED in the left overlay, with its Kconfig and .conf for the left shield only', () => {
    const files = generateShield(setDisplay(testSplit, 'left', 'oled_128x32'));
    expect(files[`${dir('test_split')}/test_split_left.overlay`]).toContain(oledNode32);
    expect(files[`${dir('test_split')}/test_split_right.overlay`]).not.toContain('oled');
    expect(files[`${dir('test_split')}/test_split.dtsi`]).not.toContain('oled');
    expect(files[`${dir('test_split')}/Kconfig.defconfig`]).toContain(`\n${displayKconfig('SHIELD_TEST_SPLIT_LEFT')}`);
    expect(files[`${dir('test_split')}/test_split_left.conf`]).toBe('# Generated by ZMK Editor from test_split.editor.json.\nCONFIG_ZMK_DISPLAY=y\n');
    expect(files[`${dir('test_split')}/test_split_right.conf`]).toBeUndefined();
  });

  it('uses the Kyria’s node for a 128×64 OLED on a one-piece keyboard', () => {
    const files = generateShield(setDisplay(testPad, undefined, 'oled_128x64'));
    const overlay = files[`${dir('test_pad')}/test_pad.overlay`] ?? '';
    expect(overlay).toContain(`        width = <128>;
        height = <64>;
        segment-offset = <0>;
        page-offset = <0>;
        display-offset = <0>;
        multiplex-ratio = <63>;
        prechargep = <0x22>;
        inversion-on;
    };`);
    expect(overlay.trimEnd().endsWith('zephyr,display = &oled;\n    };\n};')).toBe(true);
    expect(files[`${dir('test_pad')}/Kconfig.defconfig`]).toContain(displayKconfig('SHIELD_TEST_PAD'));
    expect(files[`${dir('test_pad')}/test_pad.conf`]).toContain('CONFIG_ZMK_DISPLAY=y');
  });

  it('writes nothing extra for a nice!view (it comes from ZMK’s own shields in build.yaml)', () => {
    // Only the definition file records the display; every generated ZMK file stays the same.
    const json = `${dir('test_split')}/test_split.editor.json`;
    const firmware = (files: Record<string, string>) => Object.fromEntries(Object.entries(files).filter(([path]) => path !== json));
    expect(firmware(generateShield(setDisplay(testSplit, 'left', 'nice_view')))).toEqual(firmware(generateShield(testSplit)));
  });
});

describe('generateShield: Seeed XIAO', () => {
  const xiaoPad: KeyboardHardware = { ...testPad, controller: 'seeeduino_xiao_ble', wiring: { kind: 'direct', pins: [0, 10] } };

  it('uses &xiao_d pins and requires the seeed_xiao interconnect, like ZMK’s tester_xiao', () => {
    const files = generateShield(xiaoPad);
    expect(files[`${dir('test_pad')}/test_pad.overlay`]).toContain(`        input-gpios
            = <&xiao_d  0 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>
            , <&xiao_d 10 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>
            ;`);
    expect(files[`${dir('test_pad')}/test_pad.zmk.yml`]).toContain('requires: [seeed_xiao]\n');
  });

  it('puts encoders on &xiao_d and an OLED on &xiao_i2c', () => {
    const split: KeyboardHardware = {
      ...setDisplay({ ...testSplit, controller: 'seeeduino_xiao_ble' }, 'left', 'oled_128x32'),
      encoders: [{ a: 8, b: 9 }],
    };
    const files = Object.values(generateShield(split)).join('\n');
    expect(files).toContain('a-gpios = <&xiao_d  8 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>;');
    expect(generateShield(split)[`${dir('test_split')}/test_split_left.overlay`]).toContain('&xiao_i2c {\n    status = "okay";');
    expect(files).not.toContain('pro_micro');
  });
});

describe('generateShield: display pins', () => {
  it('gives a nice!view off the adapter’s pins its own SPI bus', () => {
    const pad: KeyboardHardware = setDisplayPin(
      setDisplay({ ...testPad, wiring: { kind: 'direct', pins: [6, 7] } }, undefined, 'nice_view'),
      undefined,
      'cs',
      5,
    );
    const overlay = generateShield(pad)[`${dir('test_pad')}/test_pad.overlay`];
    expect(overlay).toContain(`&pinctrl {
    nice_view_spi_default: nice_view_spi_default {
        group1 {
            psels = <NRF_PSEL(SPIM_SCK, 0, 20)>,
                <NRF_PSEL(SPIM_MOSI, 0, 17)>;
        };
    };
    nice_view_spi_sleep: nice_view_spi_sleep {
        group1 {
            psels = <NRF_PSEL(SPIM_SCK, 0, 20)>,
                <NRF_PSEL(SPIM_MOSI, 0, 17)>;
            low-power-enable;
        };
    };
};

nice_view_spi: &pro_micro_spi {
    compatible = "nordic,nrf-spim";
    pinctrl-0 = <&nice_view_spi_default>;
    pinctrl-1 = <&nice_view_spi_sleep>;
    pinctrl-names = "default", "sleep";
    cs-gpios = <&pro_micro 5 GPIO_ACTIVE_HIGH>;
};

&pro_micro_i2c {
    status = "disabled";
};
`);
  });

  it('sets up a XIAO nice!view on its default pins, on its half only', () => {
    const split = setDisplay({ ...testSplit, controller: 'seeeduino_xiao_ble', wiring: { kind: 'matrix', diodeDirection: 'col2row', rows: [0], cols: [1, 2] } }, 'left', 'nice_view');
    const files = generateShield(split);
    const left = files[`${dir('test_split')}/test_split_left.overlay`];
    expect(left).toContain('nice_view_spi: &xiao_spi {');
    expect(left).toContain('psels = <NRF_PSEL(SPIM_SCK, 1, 13)>,\n                <NRF_PSEL(SPIM_MOSI, 1, 15)>;');
    expect(left).toContain('cs-gpios = <&xiao_d 9 GPIO_ACTIVE_HIGH>;');
    expect(left).toContain('&xiao_i2c {\n    status = "disabled";\n};');
    expect(files[`${dir('test_split')}/test_split_right.overlay`]).not.toContain('nice_view_spi');
    expect(files[`${dir('test_split')}/test_split.dtsi`]).not.toContain('nice_view_spi');
  });

  it('moves an OLED’s I2C bus to the chosen pins', () => {
    const split = setDisplayPin(
      setDisplayPin(setDisplay({ ...testSplit, controller: 'puchi_ble_v1' }, 'left', 'oled_128x32'), 'left', 'sda', 8),
      'left',
      'scl',
      9,
    );
    const left = generateShield(split)[`${dir('test_split')}/test_split_left.overlay`];
    expect(left).toContain(`&pinctrl {
    oled_i2c_default: oled_i2c_default {
        group1 {
            psels = <NRF_PSEL(TWIM_SDA, 0, 10)>,
                <NRF_PSEL(TWIM_SCL, 1, 6)>;
        };
    };
    oled_i2c_sleep: oled_i2c_sleep {
        group1 {
            psels = <NRF_PSEL(TWIM_SDA, 0, 10)>,
                <NRF_PSEL(TWIM_SCL, 1, 6)>;
            low-power-enable;
        };
    };
};

&pro_micro_i2c {
    status = "okay";
    pinctrl-0 = <&oled_i2c_default>;
    pinctrl-1 = <&oled_i2c_sleep>;
    pinctrl-names = "default", "sleep";

    oled: ssd1306@3c {`);
  });

  it('adds nothing for displays on their standard pins', () => {
    const files = Object.values(generateShield(setDisplay(setDisplay(testSplit, 'left', 'nice_view'), 'right', 'oled_128x32'))).join('\n');
    expect(files).not.toContain('nice_view_spi');
    expect(files).not.toContain('pinctrl');
  });
});

describe('staleShieldFiles', () => {
  it('lists shield files the repo’s previous definition generated and the current one no longer does', () => {
    const repo = generateShield(setDisplay(testSplit, 'left', 'oled_128x32'));
    const now = generateShield(testSplit);
    expect(staleShieldFiles(repo, 'test_split', now)).toEqual([`${dir('test_split')}/test_split_left.conf`]);
    expect(staleShieldFiles(now, 'test_split', now)).toEqual([]);
  });

  it('leaves a stale file alone when it was edited by hand', () => {
    const repo = generateShield(setDisplay(testSplit, 'left', 'oled_128x32'));
    const edited = { ...repo, [`${dir('test_split')}/test_split_left.conf`]: 'CONFIG_ZMK_DISPLAY=y\nCONFIG_MINE=y\n' };
    expect(staleShieldFiles(edited, 'test_split', generateShield(testSplit))).toEqual([]);
  });
});

describe('generateShield: shift registers', () => {
  const overlay = (hw: KeyboardHardware) => generateShield(hw)[`${dir(hw.name)}/${hw.name}.overlay`] ?? '';

  it('drives columns from the shift register and keeps the direct columns', () => {
    const text = overlay(testShiftPad);
    expect(text).toContain('            = <&shifter  0 GPIO_ACTIVE_HIGH>\n');
    expect(text).toContain('            , <&shifter  7 GPIO_ACTIVE_HIGH>\n            , <&pro_micro  6 GPIO_ACTIVE_HIGH>\n');
  });

  it('puts them on their own SPI2 bus without a nice!view', () => {
    expect(overlay(testShiftPad)).toContain(`&pinctrl {
    shift_register_spi_default: shift_register_spi_default {
        group1 {
            psels = <NRF_PSEL(SPIM_SCK, 0, 20)>,
                <NRF_PSEL(SPIM_MOSI, 0, 17)>;
        };
    };
    shift_register_spi_sleep: shift_register_spi_sleep {
        group1 {
            psels = <NRF_PSEL(SPIM_SCK, 0, 20)>,
                <NRF_PSEL(SPIM_MOSI, 0, 17)>;
            low-power-enable;
        };
    };
};

&spi2 {
    status = "okay";
    compatible = "nordic,nrf-spim";
    pinctrl-0 = <&shift_register_spi_default>;
    pinctrl-1 = <&shift_register_spi_sleep>;
    pinctrl-names = "default", "sleep";
    cs-gpios = <&pro_micro 8 GPIO_ACTIVE_LOW>;

    shifter: 595@0 {
        compatible = "zmk,gpio-595";
        status = "okay";
        gpio-controller;
        spi-max-frequency = <1000000>;
        reg = <0>;
        #gpio-cells = <2>;
        ngpios = <8>;
    };
};`);
  });

  it('shares a nice!view’s bus: two chip selects, the shift registers as device 1, no adapter', () => {
    const hw = setDisplay(testShiftPad, undefined, 'nice_view');
    const text = overlay(hw);
    expect(text).toContain('nice_view_spi: &pro_micro_spi {');
    expect(text).toContain('    cs-gpios = <&pro_micro 1 GPIO_ACTIVE_HIGH>, <&pro_micro 8 GPIO_ACTIVE_LOW>;');
    expect(text).toContain('    shifter: 595@1 {');
    expect(text).toContain('        reg = <1>;');
    expect(text).not.toContain('&spi2');
    expect(hardwareBuildTargets(hw)[0]?.shield).toBe('test_shift nice_view');
  });

  it('keeps a nice!view on the adapter next to shift registers on their own bus', () => {
    const hw = setShiftPin(setShiftPin(setShiftOwnBus(setDisplay(testShiftPad, undefined, 'nice_view'), true), 'data', 19), 'clock', 20);
    const text = overlay(hw);
    expect(text).toContain('&spi2 {');
    expect(text).toContain('<NRF_PSEL(SPIM_SCK, 0, 29)>');
    expect(text).not.toContain('nice_view_spi');
    expect(hardwareBuildTargets(hw)[0]?.shield).toBe('test_shift nice_view_adapter nice_view');
  });

  it('sits next to an OLED, whose I2C bus stays enabled', () => {
    const text = overlay(setDisplay(testShiftPad, undefined, 'oled_128x32'));
    expect(text).toContain('&spi2 {');
    expect(text).toContain('&pro_micro_i2c {\n    status = "okay";');
  });

  it('turns on SPI in Kconfig.defconfig', () => {
    expect(generateShield(testShiftPad)[`${dir('test_shift')}/Kconfig.defconfig`]).toBe(`# Generated by ZMK Editor from test_shift.editor.json.

if SHIELD_TEST_SHIFT

config ZMK_KEYBOARD_NAME
    default "Test Shift"

config SPI
    default y

endif
`);
  });
});
