// Generated by scripts/gen-keycodes.mjs from ZMK v0.3 keys.h. Do not edit.

export interface KeycodeData {
  /** Canonical name. */
  name: string;
  aliases: string[];
  deprecated: string[];
  description: string;
  page: 'key' | 'consumer' | 'gd';
  /** Defined as LS(...) of another key, e.g. EXCLAMATION. */
  shifted: boolean;
  /** The value ZMK sends for it: (page << 16) | id, with modifier bits (LS…) in bits 24–31. */
  usage: number;
}

export const KEYCODE_DATA: KeycodeData[] = [
  {
    "name": "SYSTEM_POWER",
    "aliases": [
      "SYS_PWR"
    ],
    "deprecated": [],
    "description": "System Power Down",
    "page": "gd",
    "shifted": false,
    "usage": 65665
  },
  {
    "name": "SYSTEM_SLEEP",
    "aliases": [
      "SYS_SLEEP"
    ],
    "deprecated": [],
    "description": "System Sleep",
    "page": "gd",
    "shifted": false,
    "usage": 65666
  },
  {
    "name": "SYSTEM_WAKE_UP",
    "aliases": [
      "SYS_WAKE"
    ],
    "deprecated": [],
    "description": "System Wake Up",
    "page": "gd",
    "shifted": false,
    "usage": 65667
  },
  {
    "name": "A",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard a and A",
    "page": "key",
    "shifted": false,
    "usage": 458756
  },
  {
    "name": "B",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard b and B",
    "page": "key",
    "shifted": false,
    "usage": 458757
  },
  {
    "name": "C",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard c and C",
    "page": "key",
    "shifted": false,
    "usage": 458758
  },
  {
    "name": "D",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard d and D",
    "page": "key",
    "shifted": false,
    "usage": 458759
  },
  {
    "name": "E",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard e and E",
    "page": "key",
    "shifted": false,
    "usage": 458760
  },
  {
    "name": "F",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard f and F",
    "page": "key",
    "shifted": false,
    "usage": 458761
  },
  {
    "name": "G",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard g and G",
    "page": "key",
    "shifted": false,
    "usage": 458762
  },
  {
    "name": "H",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard h and H",
    "page": "key",
    "shifted": false,
    "usage": 458763
  },
  {
    "name": "I",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard i and I",
    "page": "key",
    "shifted": false,
    "usage": 458764
  },
  {
    "name": "J",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard j and J",
    "page": "key",
    "shifted": false,
    "usage": 458765
  },
  {
    "name": "K",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard k and K",
    "page": "key",
    "shifted": false,
    "usage": 458766
  },
  {
    "name": "L",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard l and L",
    "page": "key",
    "shifted": false,
    "usage": 458767
  },
  {
    "name": "M",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard m and M",
    "page": "key",
    "shifted": false,
    "usage": 458768
  },
  {
    "name": "N",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard n and N",
    "page": "key",
    "shifted": false,
    "usage": 458769
  },
  {
    "name": "O",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard o and O",
    "page": "key",
    "shifted": false,
    "usage": 458770
  },
  {
    "name": "P",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard p and P",
    "page": "key",
    "shifted": false,
    "usage": 458771
  },
  {
    "name": "Q",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard q and Q",
    "page": "key",
    "shifted": false,
    "usage": 458772
  },
  {
    "name": "R",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard r and R",
    "page": "key",
    "shifted": false,
    "usage": 458773
  },
  {
    "name": "S",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard s and S",
    "page": "key",
    "shifted": false,
    "usage": 458774
  },
  {
    "name": "T",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard t and T",
    "page": "key",
    "shifted": false,
    "usage": 458775
  },
  {
    "name": "U",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard u and U",
    "page": "key",
    "shifted": false,
    "usage": 458776
  },
  {
    "name": "V",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard v and V",
    "page": "key",
    "shifted": false,
    "usage": 458777
  },
  {
    "name": "W",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard w and W",
    "page": "key",
    "shifted": false,
    "usage": 458778
  },
  {
    "name": "X",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard x and X",
    "page": "key",
    "shifted": false,
    "usage": 458779
  },
  {
    "name": "Y",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard y and Y",
    "page": "key",
    "shifted": false,
    "usage": 458780
  },
  {
    "name": "Z",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard z and Z",
    "page": "key",
    "shifted": false,
    "usage": 458781
  },
  {
    "name": "NUMBER_1",
    "aliases": [
      "N1"
    ],
    "deprecated": [
      "NUM_1"
    ],
    "description": "Keyboard 1 and ! (Exclamation)",
    "page": "key",
    "shifted": false,
    "usage": 458782
  },
  {
    "name": "EXCLAMATION",
    "aliases": [
      "EXCL"
    ],
    "deprecated": [
      "BANG"
    ],
    "description": "Keyboard ! (Exclamation)",
    "page": "key",
    "shifted": true,
    "usage": 34013214
  },
  {
    "name": "NUMBER_2",
    "aliases": [
      "N2"
    ],
    "deprecated": [
      "NUM_2"
    ],
    "description": "Keyboard 2 and @ (At sign)",
    "page": "key",
    "shifted": false,
    "usage": 458783
  },
  {
    "name": "AT_SIGN",
    "aliases": [
      "AT"
    ],
    "deprecated": [
      "ATSN"
    ],
    "description": "Keyboard @ (At sign)",
    "page": "key",
    "shifted": true,
    "usage": 34013215
  },
  {
    "name": "NUMBER_3",
    "aliases": [
      "N3"
    ],
    "deprecated": [
      "NUM_3"
    ],
    "description": "Keyboard 3 and # (Hash/Number)",
    "page": "key",
    "shifted": false,
    "usage": 458784
  },
  {
    "name": "HASH",
    "aliases": [
      "POUND"
    ],
    "deprecated": [],
    "description": "Keyboard # (Hash/Number)",
    "page": "key",
    "shifted": true,
    "usage": 34013216
  },
  {
    "name": "NUMBER_4",
    "aliases": [
      "N4"
    ],
    "deprecated": [
      "NUM_4"
    ],
    "description": "Keyboard 4 and $ (Dollar)",
    "page": "key",
    "shifted": false,
    "usage": 458785
  },
  {
    "name": "DOLLAR",
    "aliases": [
      "DLLR"
    ],
    "deprecated": [],
    "description": "Keyboard $ (Dollar)",
    "page": "key",
    "shifted": true,
    "usage": 34013217
  },
  {
    "name": "NUMBER_5",
    "aliases": [
      "N5"
    ],
    "deprecated": [
      "NUM_5"
    ],
    "description": "Keyboard 5 and % (Percent)",
    "page": "key",
    "shifted": false,
    "usage": 458786
  },
  {
    "name": "PERCENT",
    "aliases": [
      "PRCNT"
    ],
    "deprecated": [
      "PRCT"
    ],
    "description": "Keyboard % (Percent)",
    "page": "key",
    "shifted": true,
    "usage": 34013218
  },
  {
    "name": "NUMBER_6",
    "aliases": [
      "N6"
    ],
    "deprecated": [
      "NUM_6"
    ],
    "description": "Keyboard 6 and ^ (Caret)",
    "page": "key",
    "shifted": false,
    "usage": 458787
  },
  {
    "name": "CARET",
    "aliases": [],
    "deprecated": [
      "CRRT"
    ],
    "description": "Keyboard ^ (Caret)",
    "page": "key",
    "shifted": true,
    "usage": 34013219
  },
  {
    "name": "NUMBER_7",
    "aliases": [
      "N7"
    ],
    "deprecated": [
      "NUM_7"
    ],
    "description": "Keyboard 7 and & (Ampersand)",
    "page": "key",
    "shifted": false,
    "usage": 458788
  },
  {
    "name": "AMPERSAND",
    "aliases": [
      "AMPS"
    ],
    "deprecated": [],
    "description": "Keyboard & (Ampersand)",
    "page": "key",
    "shifted": true,
    "usage": 34013220
  },
  {
    "name": "NUMBER_8",
    "aliases": [
      "N8"
    ],
    "deprecated": [
      "NUM_8"
    ],
    "description": "Keyboard 8 and * (Asterisk)",
    "page": "key",
    "shifted": false,
    "usage": 458789
  },
  {
    "name": "ASTERISK",
    "aliases": [
      "ASTRK",
      "STAR"
    ],
    "deprecated": [],
    "description": "Keyboard * (Asterisk)",
    "page": "key",
    "shifted": true,
    "usage": 34013221
  },
  {
    "name": "NUMBER_9",
    "aliases": [
      "N9"
    ],
    "deprecated": [
      "NUM_9"
    ],
    "description": "Keyboard 9 and ( (Left Parenthesis)",
    "page": "key",
    "shifted": false,
    "usage": 458790
  },
  {
    "name": "LEFT_PARENTHESIS",
    "aliases": [
      "LPAR"
    ],
    "deprecated": [
      "LPRN"
    ],
    "description": "Keyboard ( (Left Parenthesis)",
    "page": "key",
    "shifted": true,
    "usage": 34013222
  },
  {
    "name": "NUMBER_0",
    "aliases": [
      "N0"
    ],
    "deprecated": [
      "NUM_0"
    ],
    "description": "Keyboard 0 and ) (Right Parenthesis)",
    "page": "key",
    "shifted": false,
    "usage": 458791
  },
  {
    "name": "RIGHT_PARENTHESIS",
    "aliases": [
      "RPAR"
    ],
    "deprecated": [
      "RPRN"
    ],
    "description": "Keyboard ) (Right Parenthesis)",
    "page": "key",
    "shifted": true,
    "usage": 34013223
  },
  {
    "name": "RETURN",
    "aliases": [
      "ENTER",
      "RET"
    ],
    "deprecated": [],
    "description": "Keyboard Return (Enter)",
    "page": "key",
    "shifted": false,
    "usage": 458792
  },
  {
    "name": "ESCAPE",
    "aliases": [
      "ESC"
    ],
    "deprecated": [],
    "description": "Keyboard Escape",
    "page": "key",
    "shifted": false,
    "usage": 458793
  },
  {
    "name": "BACKSPACE",
    "aliases": [
      "BSPC"
    ],
    "deprecated": [
      "BKSP"
    ],
    "description": "Keyboard Backspace",
    "page": "key",
    "shifted": false,
    "usage": 458794
  },
  {
    "name": "TAB",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Tab",
    "page": "key",
    "shifted": false,
    "usage": 458795
  },
  {
    "name": "SPACE",
    "aliases": [],
    "deprecated": [
      "SPC"
    ],
    "description": "Keyboard Space",
    "page": "key",
    "shifted": false,
    "usage": 458796
  },
  {
    "name": "MINUS",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard - and _ (Minus and Underscore)",
    "page": "key",
    "shifted": false,
    "usage": 458797
  },
  {
    "name": "UNDERSCORE",
    "aliases": [
      "UNDER"
    ],
    "deprecated": [],
    "description": "Keyboard _ (Underscore)",
    "page": "key",
    "shifted": true,
    "usage": 34013229
  },
  {
    "name": "EQUAL",
    "aliases": [],
    "deprecated": [
      "EQL"
    ],
    "description": "Keyboard = and + (Equal and Plus)",
    "page": "key",
    "shifted": false,
    "usage": 458798
  },
  {
    "name": "PLUS",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard + (Plus)",
    "page": "key",
    "shifted": true,
    "usage": 34013230
  },
  {
    "name": "LEFT_BRACKET",
    "aliases": [
      "LBKT"
    ],
    "deprecated": [],
    "description": "Keyboard [ and { (Left Bracket and Left Brace)",
    "page": "key",
    "shifted": false,
    "usage": 458799
  },
  {
    "name": "LEFT_BRACE",
    "aliases": [
      "LBRC"
    ],
    "deprecated": [
      "LCUR"
    ],
    "description": "Keyboard { (Left Brace)",
    "page": "key",
    "shifted": true,
    "usage": 34013231
  },
  {
    "name": "RIGHT_BRACKET",
    "aliases": [
      "RBKT"
    ],
    "deprecated": [],
    "description": "Keyboard ] and } (Right Bracket and Right Brace)",
    "page": "key",
    "shifted": false,
    "usage": 458800
  },
  {
    "name": "RIGHT_BRACE",
    "aliases": [
      "RBRC"
    ],
    "deprecated": [
      "RCUR"
    ],
    "description": "Keyboard } (Right Brace)",
    "page": "key",
    "shifted": true,
    "usage": 34013232
  },
  {
    "name": "BACKSLASH",
    "aliases": [
      "BSLH"
    ],
    "deprecated": [],
    "description": "Keyboard \\ and | (Backslash and Pipe)",
    "page": "key",
    "shifted": false,
    "usage": 458801
  },
  {
    "name": "PIPE",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard | (Pipe)",
    "page": "key",
    "shifted": true,
    "usage": 34013233
  },
  {
    "name": "NON_US_HASH",
    "aliases": [
      "NUHS"
    ],
    "deprecated": [],
    "description": "Keyboard Non-US # and ~ (Non-US Hash/Number and Tilde)",
    "page": "key",
    "shifted": false,
    "usage": 458802
  },
  {
    "name": "TILDE2",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard ~ (Tilde)",
    "page": "key",
    "shifted": true,
    "usage": 34013234
  },
  {
    "name": "SEMICOLON",
    "aliases": [
      "SEMI"
    ],
    "deprecated": [
      "SCLN"
    ],
    "description": "Keyboard ; and : (Semicolon and Colon)",
    "page": "key",
    "shifted": false,
    "usage": 458803
  },
  {
    "name": "COLON",
    "aliases": [],
    "deprecated": [
      "COLN"
    ],
    "description": "Keyboard : (Colon)",
    "page": "key",
    "shifted": true,
    "usage": 34013235
  },
  {
    "name": "SINGLE_QUOTE",
    "aliases": [
      "SQT",
      "APOSTROPHE",
      "APOS"
    ],
    "deprecated": [
      "QUOT"
    ],
    "description": "Keyboard ' and \" (Apostrophe and Quote)",
    "page": "key",
    "shifted": false,
    "usage": 458804
  },
  {
    "name": "DOUBLE_QUOTES",
    "aliases": [
      "DQT"
    ],
    "deprecated": [],
    "description": "Keyboard \" (Quote)",
    "page": "key",
    "shifted": true,
    "usage": 34013236
  },
  {
    "name": "GRAVE",
    "aliases": [],
    "deprecated": [
      "GRAV"
    ],
    "description": "Keyboard ` and ~ (Grave Accent and Tilde)",
    "page": "key",
    "shifted": false,
    "usage": 458805
  },
  {
    "name": "TILDE",
    "aliases": [],
    "deprecated": [
      "TILD"
    ],
    "description": "Keyboard ~ (Tilde)",
    "page": "key",
    "shifted": true,
    "usage": 34013237
  },
  {
    "name": "COMMA",
    "aliases": [],
    "deprecated": [
      "CMMA"
    ],
    "description": "Keyboard , and < (Comma and Less Than)",
    "page": "key",
    "shifted": false,
    "usage": 458806
  },
  {
    "name": "LESS_THAN",
    "aliases": [
      "LT"
    ],
    "deprecated": [
      "LABT"
    ],
    "description": "Keyboard < (Less Than)",
    "page": "key",
    "shifted": true,
    "usage": 34013238
  },
  {
    "name": "PERIOD",
    "aliases": [
      "DOT"
    ],
    "deprecated": [],
    "description": "Keyboard . and > (Period and Greater Than)",
    "page": "key",
    "shifted": false,
    "usage": 458807
  },
  {
    "name": "GREATER_THAN",
    "aliases": [
      "GT"
    ],
    "deprecated": [
      "RABT"
    ],
    "description": "Keyboard > (Greater Than)",
    "page": "key",
    "shifted": true,
    "usage": 34013239
  },
  {
    "name": "SLASH",
    "aliases": [
      "FSLH"
    ],
    "deprecated": [],
    "description": "Keyboard / and ? (Forward Slash and Question)",
    "page": "key",
    "shifted": false,
    "usage": 458808
  },
  {
    "name": "QUESTION",
    "aliases": [
      "QMARK"
    ],
    "deprecated": [],
    "description": "Keyboard ? (Question)",
    "page": "key",
    "shifted": true,
    "usage": 34013240
  },
  {
    "name": "CAPSLOCK",
    "aliases": [
      "CAPS",
      "CLCK"
    ],
    "deprecated": [],
    "description": "Keyboard Caps Lock",
    "page": "key",
    "shifted": false,
    "usage": 458809
  },
  {
    "name": "F1",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F1",
    "page": "key",
    "shifted": false,
    "usage": 458810
  },
  {
    "name": "F2",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F2",
    "page": "key",
    "shifted": false,
    "usage": 458811
  },
  {
    "name": "F3",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F3",
    "page": "key",
    "shifted": false,
    "usage": 458812
  },
  {
    "name": "F4",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F4",
    "page": "key",
    "shifted": false,
    "usage": 458813
  },
  {
    "name": "F5",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F5",
    "page": "key",
    "shifted": false,
    "usage": 458814
  },
  {
    "name": "F6",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F6",
    "page": "key",
    "shifted": false,
    "usage": 458815
  },
  {
    "name": "F7",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F7",
    "page": "key",
    "shifted": false,
    "usage": 458816
  },
  {
    "name": "F8",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F8",
    "page": "key",
    "shifted": false,
    "usage": 458817
  },
  {
    "name": "F9",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F9",
    "page": "key",
    "shifted": false,
    "usage": 458818
  },
  {
    "name": "F10",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F10",
    "page": "key",
    "shifted": false,
    "usage": 458819
  },
  {
    "name": "F11",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F11",
    "page": "key",
    "shifted": false,
    "usage": 458820
  },
  {
    "name": "F12",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F12",
    "page": "key",
    "shifted": false,
    "usage": 458821
  },
  {
    "name": "PRINTSCREEN",
    "aliases": [
      "PSCRN"
    ],
    "deprecated": [
      "PRSC"
    ],
    "description": "Keyboard Print Screen",
    "page": "key",
    "shifted": false,
    "usage": 458822
  },
  {
    "name": "SCROLLLOCK",
    "aliases": [
      "SLCK"
    ],
    "deprecated": [
      "SCLK"
    ],
    "description": "Keyboard Scroll Lock",
    "page": "key",
    "shifted": false,
    "usage": 458823
  },
  {
    "name": "PAUSE_BREAK",
    "aliases": [],
    "deprecated": [
      "PAUS"
    ],
    "description": "Keyboard Pause/Break",
    "page": "key",
    "shifted": false,
    "usage": 458824
  },
  {
    "name": "INSERT",
    "aliases": [
      "INS"
    ],
    "deprecated": [],
    "description": "Keyboard Insert",
    "page": "key",
    "shifted": false,
    "usage": 458825
  },
  {
    "name": "HOME",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Home",
    "page": "key",
    "shifted": false,
    "usage": 458826
  },
  {
    "name": "PAGE_UP",
    "aliases": [
      "PG_UP"
    ],
    "deprecated": [
      "PGUP"
    ],
    "description": "Keyboard Page Up",
    "page": "key",
    "shifted": false,
    "usage": 458827
  },
  {
    "name": "DELETE",
    "aliases": [
      "DEL"
    ],
    "deprecated": [],
    "description": "Keyboard Delete",
    "page": "key",
    "shifted": false,
    "usage": 458828
  },
  {
    "name": "END",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard End",
    "page": "key",
    "shifted": false,
    "usage": 458829
  },
  {
    "name": "PAGE_DOWN",
    "aliases": [
      "PG_DN"
    ],
    "deprecated": [
      "PGDN"
    ],
    "description": "Keyboard Page Down",
    "page": "key",
    "shifted": false,
    "usage": 458830
  },
  {
    "name": "RIGHT_ARROW",
    "aliases": [
      "RIGHT"
    ],
    "deprecated": [
      "RARW"
    ],
    "description": "Keyboard Right Arrow",
    "page": "key",
    "shifted": false,
    "usage": 458831
  },
  {
    "name": "LEFT_ARROW",
    "aliases": [
      "LEFT"
    ],
    "deprecated": [
      "LARW"
    ],
    "description": "Keyboard Left Arrow",
    "page": "key",
    "shifted": false,
    "usage": 458832
  },
  {
    "name": "DOWN_ARROW",
    "aliases": [
      "DOWN"
    ],
    "deprecated": [
      "DARW"
    ],
    "description": "Keyboard Down Arrow",
    "page": "key",
    "shifted": false,
    "usage": 458833
  },
  {
    "name": "UP_ARROW",
    "aliases": [
      "UP"
    ],
    "deprecated": [
      "UARW"
    ],
    "description": "Keyboard Up Arrow",
    "page": "key",
    "shifted": false,
    "usage": 458834
  },
  {
    "name": "KP_NUMLOCK",
    "aliases": [
      "KP_NUM",
      "KP_NLCK"
    ],
    "deprecated": [],
    "description": "Keypad Numlock and Clear",
    "page": "key",
    "shifted": false,
    "usage": 458835
  },
  {
    "name": "CLEAR2",
    "aliases": [],
    "deprecated": [],
    "description": "Keypad Clear",
    "page": "key",
    "shifted": true,
    "usage": 34013267
  },
  {
    "name": "KP_DIVIDE",
    "aliases": [
      "KP_SLASH"
    ],
    "deprecated": [
      "KDIV"
    ],
    "description": "Keypad / (Slash/Divide)",
    "page": "key",
    "shifted": false,
    "usage": 458836
  },
  {
    "name": "KP_MULTIPLY",
    "aliases": [
      "KP_ASTERISK"
    ],
    "deprecated": [
      "KMLT"
    ],
    "description": "Keypad * (Multiply)",
    "page": "key",
    "shifted": false,
    "usage": 458837
  },
  {
    "name": "KP_MINUS",
    "aliases": [
      "KP_SUBTRACT"
    ],
    "deprecated": [
      "KMIN"
    ],
    "description": "Keypad - (Minus)",
    "page": "key",
    "shifted": false,
    "usage": 458838
  },
  {
    "name": "KP_PLUS",
    "aliases": [],
    "deprecated": [
      "KPLS"
    ],
    "description": "Keypad + (Plus)",
    "page": "key",
    "shifted": false,
    "usage": 458839
  },
  {
    "name": "KP_ENTER",
    "aliases": [],
    "deprecated": [],
    "description": "Keypad Enter",
    "page": "key",
    "shifted": false,
    "usage": 458840
  },
  {
    "name": "KP_NUMBER_1",
    "aliases": [
      "KP_N1"
    ],
    "deprecated": [],
    "description": "Keypad 1",
    "page": "key",
    "shifted": false,
    "usage": 458841
  },
  {
    "name": "KP_NUMBER_2",
    "aliases": [
      "KP_N2"
    ],
    "deprecated": [],
    "description": "Keypad 2",
    "page": "key",
    "shifted": false,
    "usage": 458842
  },
  {
    "name": "KP_NUMBER_3",
    "aliases": [
      "KP_N3"
    ],
    "deprecated": [],
    "description": "Keypad 3",
    "page": "key",
    "shifted": false,
    "usage": 458843
  },
  {
    "name": "KP_NUMBER_4",
    "aliases": [
      "KP_N4"
    ],
    "deprecated": [],
    "description": "Keypad 4",
    "page": "key",
    "shifted": false,
    "usage": 458844
  },
  {
    "name": "KP_NUMBER_5",
    "aliases": [
      "KP_N5"
    ],
    "deprecated": [],
    "description": "Keypad 5",
    "page": "key",
    "shifted": false,
    "usage": 458845
  },
  {
    "name": "KP_NUMBER_6",
    "aliases": [
      "KP_N6"
    ],
    "deprecated": [],
    "description": "Keypad 6",
    "page": "key",
    "shifted": false,
    "usage": 458846
  },
  {
    "name": "KP_NUMBER_7",
    "aliases": [
      "KP_N7"
    ],
    "deprecated": [],
    "description": "Keypad 7",
    "page": "key",
    "shifted": false,
    "usage": 458847
  },
  {
    "name": "KP_NUMBER_8",
    "aliases": [
      "KP_N8"
    ],
    "deprecated": [],
    "description": "Keypad 8",
    "page": "key",
    "shifted": false,
    "usage": 458848
  },
  {
    "name": "KP_NUMBER_9",
    "aliases": [
      "KP_N9"
    ],
    "deprecated": [],
    "description": "Keypad 9",
    "page": "key",
    "shifted": false,
    "usage": 458849
  },
  {
    "name": "KP_NUMBER_0",
    "aliases": [
      "KP_N0"
    ],
    "deprecated": [],
    "description": "Keypad 0",
    "page": "key",
    "shifted": false,
    "usage": 458850
  },
  {
    "name": "KP_DOT",
    "aliases": [],
    "deprecated": [],
    "description": "Keypad . (Dot)",
    "page": "key",
    "shifted": false,
    "usage": 458851
  },
  {
    "name": "NON_US_BACKSLASH",
    "aliases": [
      "NON_US_BSLH",
      "NUBS"
    ],
    "deprecated": [],
    "description": "Keyboard Non-US \\ and | (Non-us Backslash and Pipe)",
    "page": "key",
    "shifted": false,
    "usage": 458852
  },
  {
    "name": "PIPE2",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Pipe",
    "page": "key",
    "shifted": true,
    "usage": 34013284
  },
  {
    "name": "K_APPLICATION",
    "aliases": [
      "K_APP",
      "K_CONTEXT_MENU",
      "K_CMENU"
    ],
    "deprecated": [
      "GUI"
    ],
    "description": "Keyboard Application (Context Menu)",
    "page": "key",
    "shifted": false,
    "usage": 458853
  },
  {
    "name": "K_POWER",
    "aliases": [
      "K_PWR"
    ],
    "deprecated": [],
    "description": "Keyboard Power",
    "page": "key",
    "shifted": false,
    "usage": 458854
  },
  {
    "name": "KP_EQUAL",
    "aliases": [],
    "deprecated": [],
    "description": "Keypad = (Equal)",
    "page": "key",
    "shifted": false,
    "usage": 458855
  },
  {
    "name": "F13",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F13",
    "page": "key",
    "shifted": false,
    "usage": 458856
  },
  {
    "name": "F14",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F14",
    "page": "key",
    "shifted": false,
    "usage": 458857
  },
  {
    "name": "F15",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F15",
    "page": "key",
    "shifted": false,
    "usage": 458858
  },
  {
    "name": "F16",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F16",
    "page": "key",
    "shifted": false,
    "usage": 458859
  },
  {
    "name": "F17",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F17",
    "page": "key",
    "shifted": false,
    "usage": 458860
  },
  {
    "name": "F18",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F18",
    "page": "key",
    "shifted": false,
    "usage": 458861
  },
  {
    "name": "F19",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F19",
    "page": "key",
    "shifted": false,
    "usage": 458862
  },
  {
    "name": "F20",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F20",
    "page": "key",
    "shifted": false,
    "usage": 458863
  },
  {
    "name": "F21",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F21",
    "page": "key",
    "shifted": false,
    "usage": 458864
  },
  {
    "name": "F22",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F22",
    "page": "key",
    "shifted": false,
    "usage": 458865
  },
  {
    "name": "F23",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F23",
    "page": "key",
    "shifted": false,
    "usage": 458866
  },
  {
    "name": "F24",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard F24",
    "page": "key",
    "shifted": false,
    "usage": 458867
  },
  {
    "name": "K_EXECUTE",
    "aliases": [
      "K_EXEC"
    ],
    "deprecated": [],
    "description": "Keyboard Execute",
    "page": "key",
    "shifted": false,
    "usage": 458868
  },
  {
    "name": "K_HELP",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Help",
    "page": "key",
    "shifted": false,
    "usage": 458869
  },
  {
    "name": "K_MENU",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Menu",
    "page": "key",
    "shifted": false,
    "usage": 458870
  },
  {
    "name": "K_SELECT",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Select",
    "page": "key",
    "shifted": false,
    "usage": 458871
  },
  {
    "name": "K_STOP",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Stop",
    "page": "key",
    "shifted": false,
    "usage": 458872
  },
  {
    "name": "K_AGAIN",
    "aliases": [
      "K_REDO"
    ],
    "deprecated": [],
    "description": "Keyboard Again",
    "page": "key",
    "shifted": false,
    "usage": 458873
  },
  {
    "name": "K_UNDO",
    "aliases": [],
    "deprecated": [
      "UNDO"
    ],
    "description": "Keyboard Undo",
    "page": "key",
    "shifted": false,
    "usage": 458874
  },
  {
    "name": "K_CUT",
    "aliases": [],
    "deprecated": [
      "CUT"
    ],
    "description": "Keyboard Cut",
    "page": "key",
    "shifted": false,
    "usage": 458875
  },
  {
    "name": "K_COPY",
    "aliases": [],
    "deprecated": [
      "COPY"
    ],
    "description": "Keyboard Copy",
    "page": "key",
    "shifted": false,
    "usage": 458876
  },
  {
    "name": "K_PASTE",
    "aliases": [],
    "deprecated": [
      "PSTE"
    ],
    "description": "Keyboard Paste",
    "page": "key",
    "shifted": false,
    "usage": 458877
  },
  {
    "name": "K_FIND",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Find",
    "page": "key",
    "shifted": false,
    "usage": 458878
  },
  {
    "name": "K_MUTE",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Mute",
    "page": "key",
    "shifted": false,
    "usage": 458879
  },
  {
    "name": "K_VOLUME_UP",
    "aliases": [
      "K_VOL_UP"
    ],
    "deprecated": [
      "VOLU"
    ],
    "description": "Keyboard Volume Up",
    "page": "key",
    "shifted": false,
    "usage": 458880
  },
  {
    "name": "K_VOLUME_DOWN",
    "aliases": [
      "K_VOL_DN"
    ],
    "deprecated": [
      "VOLD"
    ],
    "description": "Keyboard Volume Down",
    "page": "key",
    "shifted": false,
    "usage": 458881
  },
  {
    "name": "LOCKING_CAPS",
    "aliases": [
      "LCAPS"
    ],
    "deprecated": [],
    "description": "Keyboard Locking Caps Lock",
    "page": "key",
    "shifted": false,
    "usage": 458882
  },
  {
    "name": "LOCKING_NUM",
    "aliases": [
      "LNLCK"
    ],
    "deprecated": [],
    "description": "Keyboard Locking Num Lock",
    "page": "key",
    "shifted": false,
    "usage": 458883
  },
  {
    "name": "LOCKING_SCROLL",
    "aliases": [
      "LSLCK"
    ],
    "deprecated": [],
    "description": "Keyboard Locking Scroll Lock",
    "page": "key",
    "shifted": false,
    "usage": 458884
  },
  {
    "name": "KP_COMMA",
    "aliases": [],
    "deprecated": [],
    "description": "Keypad , (Comma)",
    "page": "key",
    "shifted": false,
    "usage": 458885
  },
  {
    "name": "KP_EQUAL_AS400",
    "aliases": [],
    "deprecated": [],
    "description": "Keypad = (Equal) AS/400",
    "page": "key",
    "shifted": false,
    "usage": 458886
  },
  {
    "name": "INTERNATIONAL_1",
    "aliases": [
      "INT1",
      "INT_RO"
    ],
    "deprecated": [],
    "description": "Keyboard International 1",
    "page": "key",
    "shifted": false,
    "usage": 458887
  },
  {
    "name": "INTERNATIONAL_2",
    "aliases": [
      "INT2",
      "INT_KATAKANAHIRAGANA",
      "INT_KANA"
    ],
    "deprecated": [],
    "description": "Keyboard International 2",
    "page": "key",
    "shifted": false,
    "usage": 458888
  },
  {
    "name": "INTERNATIONAL_3",
    "aliases": [
      "INT3",
      "INT_YEN"
    ],
    "deprecated": [],
    "description": "Keyboard International 3",
    "page": "key",
    "shifted": false,
    "usage": 458889
  },
  {
    "name": "INTERNATIONAL_4",
    "aliases": [
      "INT4",
      "INT_HENKAN"
    ],
    "deprecated": [],
    "description": "Keyboard International 4",
    "page": "key",
    "shifted": false,
    "usage": 458890
  },
  {
    "name": "INTERNATIONAL_5",
    "aliases": [
      "INT5",
      "INT_MUHENKAN"
    ],
    "deprecated": [],
    "description": "Keyboard International 5",
    "page": "key",
    "shifted": false,
    "usage": 458891
  },
  {
    "name": "INTERNATIONAL_6",
    "aliases": [
      "INT6",
      "INT_KPJPCOMMA"
    ],
    "deprecated": [],
    "description": "Keyboard International 6",
    "page": "key",
    "shifted": false,
    "usage": 458892
  },
  {
    "name": "INTERNATIONAL_7",
    "aliases": [
      "INT7"
    ],
    "deprecated": [],
    "description": "Keyboard International 7",
    "page": "key",
    "shifted": false,
    "usage": 458893
  },
  {
    "name": "INTERNATIONAL_8",
    "aliases": [
      "INT8"
    ],
    "deprecated": [],
    "description": "Keyboard International 8",
    "page": "key",
    "shifted": false,
    "usage": 458894
  },
  {
    "name": "INTERNATIONAL_9",
    "aliases": [
      "INT9"
    ],
    "deprecated": [],
    "description": "Keyboard International 9",
    "page": "key",
    "shifted": false,
    "usage": 458895
  },
  {
    "name": "LANGUAGE_1",
    "aliases": [
      "LANG1",
      "LANG_HANGEUL"
    ],
    "deprecated": [],
    "description": "Keyboard Language 1",
    "page": "key",
    "shifted": false,
    "usage": 458896
  },
  {
    "name": "LANGUAGE_2",
    "aliases": [
      "LANG2",
      "LANG_HANJA"
    ],
    "deprecated": [],
    "description": "Keyboard Language 2",
    "page": "key",
    "shifted": false,
    "usage": 458897
  },
  {
    "name": "LANGUAGE_3",
    "aliases": [
      "LANG3",
      "LANG_KATAKANA"
    ],
    "deprecated": [],
    "description": "Keyboard Language 3",
    "page": "key",
    "shifted": false,
    "usage": 458898
  },
  {
    "name": "LANGUAGE_4",
    "aliases": [
      "LANG4",
      "LANG_HIRAGANA"
    ],
    "deprecated": [],
    "description": "Keyboard Language 4",
    "page": "key",
    "shifted": false,
    "usage": 458899
  },
  {
    "name": "LANGUAGE_5",
    "aliases": [
      "LANG5",
      "LANG_ZENKAKUHANKAKU"
    ],
    "deprecated": [],
    "description": "Keyboard Language 5",
    "page": "key",
    "shifted": false,
    "usage": 458900
  },
  {
    "name": "LANGUAGE_6",
    "aliases": [
      "LANG6"
    ],
    "deprecated": [],
    "description": "Keyboard Language 6",
    "page": "key",
    "shifted": false,
    "usage": 458901
  },
  {
    "name": "LANGUAGE_7",
    "aliases": [
      "LANG7"
    ],
    "deprecated": [],
    "description": "Keyboard Language 7",
    "page": "key",
    "shifted": false,
    "usage": 458902
  },
  {
    "name": "LANGUAGE_8",
    "aliases": [
      "LANG8"
    ],
    "deprecated": [],
    "description": "Keyboard Language 8",
    "page": "key",
    "shifted": false,
    "usage": 458903
  },
  {
    "name": "LANGUAGE_9",
    "aliases": [
      "LANG9"
    ],
    "deprecated": [],
    "description": "Keyboard Language 9",
    "page": "key",
    "shifted": false,
    "usage": 458904
  },
  {
    "name": "ALT_ERASE",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Alternate Erase",
    "page": "key",
    "shifted": false,
    "usage": 458905
  },
  {
    "name": "SYSREQ",
    "aliases": [
      "ATTENTION"
    ],
    "deprecated": [],
    "description": "Keyboard SysReq/Attention",
    "page": "key",
    "shifted": false,
    "usage": 458906
  },
  {
    "name": "K_CANCEL",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Cancel",
    "page": "key",
    "shifted": false,
    "usage": 458907
  },
  {
    "name": "CLEAR",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Clear",
    "page": "key",
    "shifted": false,
    "usage": 458908
  },
  {
    "name": "PRIOR",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Prior",
    "page": "key",
    "shifted": false,
    "usage": 458909
  },
  {
    "name": "RETURN2",
    "aliases": [
      "RET2"
    ],
    "deprecated": [],
    "description": "Keyboard Return",
    "page": "key",
    "shifted": false,
    "usage": 458910
  },
  {
    "name": "SEPARATOR",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Separator",
    "page": "key",
    "shifted": false,
    "usage": 458911
  },
  {
    "name": "OUT",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Out",
    "page": "key",
    "shifted": false,
    "usage": 458912
  },
  {
    "name": "OPER",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Oper",
    "page": "key",
    "shifted": false,
    "usage": 458913
  },
  {
    "name": "CLEAR_AGAIN",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Clear/Again",
    "page": "key",
    "shifted": false,
    "usage": 458914
  },
  {
    "name": "CRSEL",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard CrSel/Props",
    "page": "key",
    "shifted": false,
    "usage": 458915
  },
  {
    "name": "EXSEL",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard ExSel",
    "page": "key",
    "shifted": false,
    "usage": 458916
  },
  {
    "name": "CURU",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Currency Unit",
    "page": "key",
    "shifted": false,
    "usage": 458932
  },
  {
    "name": "KP_LEFT_PARENTHESIS",
    "aliases": [
      "KP_LPAR"
    ],
    "deprecated": [],
    "description": "Keypad ( (Left Parenthesis)",
    "page": "key",
    "shifted": false,
    "usage": 458934
  },
  {
    "name": "KP_RIGHT_PARENTHESIS",
    "aliases": [
      "KP_RPAR"
    ],
    "deprecated": [],
    "description": "Keypad ) (Right Parenthesis)",
    "page": "key",
    "shifted": false,
    "usage": 458935
  },
  {
    "name": "KSPC",
    "aliases": [],
    "deprecated": [],
    "description": "Keypad Space",
    "page": "key",
    "shifted": false,
    "usage": 458957
  },
  {
    "name": "KP_CLEAR",
    "aliases": [],
    "deprecated": [],
    "description": "Keypad Clear",
    "page": "key",
    "shifted": false,
    "usage": 458968
  },
  {
    "name": "LEFT_CONTROL",
    "aliases": [
      "LCTRL"
    ],
    "deprecated": [
      "LCTL"
    ],
    "description": "Keyboard Left Control",
    "page": "key",
    "shifted": false,
    "usage": 458976
  },
  {
    "name": "LEFT_SHIFT",
    "aliases": [
      "LSHIFT",
      "LSHFT"
    ],
    "deprecated": [
      "LSFT"
    ],
    "description": "Keyboard Left Shift",
    "page": "key",
    "shifted": false,
    "usage": 458977
  },
  {
    "name": "LEFT_ALT",
    "aliases": [
      "LALT"
    ],
    "deprecated": [],
    "description": "Keyboard Left Alt",
    "page": "key",
    "shifted": false,
    "usage": 458978
  },
  {
    "name": "LEFT_GUI",
    "aliases": [
      "LGUI",
      "LEFT_WIN",
      "LWIN",
      "LEFT_COMMAND",
      "LCMD",
      "LEFT_META",
      "LMETA"
    ],
    "deprecated": [],
    "description": "Keyboard Left GUI (Windows / Command / Meta)",
    "page": "key",
    "shifted": false,
    "usage": 458979
  },
  {
    "name": "RIGHT_CONTROL",
    "aliases": [
      "RCTRL"
    ],
    "deprecated": [
      "RCTL"
    ],
    "description": "Keyboard Right Control",
    "page": "key",
    "shifted": false,
    "usage": 458980
  },
  {
    "name": "RIGHT_SHIFT",
    "aliases": [
      "RSHIFT",
      "RSHFT"
    ],
    "deprecated": [
      "RSFT"
    ],
    "description": "Keyboard Right Shift",
    "page": "key",
    "shifted": false,
    "usage": 458981
  },
  {
    "name": "RIGHT_ALT",
    "aliases": [
      "RALT"
    ],
    "deprecated": [],
    "description": "Keyboard Right Alt",
    "page": "key",
    "shifted": false,
    "usage": 458982
  },
  {
    "name": "RIGHT_GUI",
    "aliases": [
      "RGUI",
      "RIGHT_WIN",
      "RWIN",
      "RIGHT_COMMAND",
      "RCMD",
      "RIGHT_META",
      "RMETA"
    ],
    "deprecated": [],
    "description": "Keyboard Right GUI (Windows / Command / Meta)",
    "page": "key",
    "shifted": false,
    "usage": 458983
  },
  {
    "name": "K_PLAY_PAUSE",
    "aliases": [
      "K_PP"
    ],
    "deprecated": [],
    "description": "Keyboard Play/Pause",
    "page": "key",
    "shifted": false,
    "usage": 458984
  },
  {
    "name": "K_STOP2",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Stop",
    "page": "key",
    "shifted": false,
    "usage": 458985
  },
  {
    "name": "K_PREVIOUS",
    "aliases": [
      "K_PREV"
    ],
    "deprecated": [],
    "description": "Keyboard Previous",
    "page": "key",
    "shifted": false,
    "usage": 458986
  },
  {
    "name": "K_NEXT",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Next",
    "page": "key",
    "shifted": false,
    "usage": 458987
  },
  {
    "name": "K_EJECT",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Eject",
    "page": "key",
    "shifted": false,
    "usage": 458988
  },
  {
    "name": "K_VOLUME_UP2",
    "aliases": [
      "K_VOL_UP2"
    ],
    "deprecated": [],
    "description": "Keyboard Volume Up",
    "page": "key",
    "shifted": false,
    "usage": 458989
  },
  {
    "name": "K_VOLUME_DOWN2",
    "aliases": [
      "K_VOL_DN2"
    ],
    "deprecated": [],
    "description": "Keyboard Volume Down",
    "page": "key",
    "shifted": false,
    "usage": 458990
  },
  {
    "name": "K_MUTE2",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Mute",
    "page": "key",
    "shifted": false,
    "usage": 458991
  },
  {
    "name": "K_WWW",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard WWW",
    "page": "key",
    "shifted": false,
    "usage": 458992
  },
  {
    "name": "K_BACK",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Back",
    "page": "key",
    "shifted": false,
    "usage": 458993
  },
  {
    "name": "K_FORWARD",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Forward",
    "page": "key",
    "shifted": false,
    "usage": 458994
  },
  {
    "name": "K_STOP3",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Stop",
    "page": "key",
    "shifted": false,
    "usage": 458995
  },
  {
    "name": "K_FIND2",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Find",
    "page": "key",
    "shifted": false,
    "usage": 458996
  },
  {
    "name": "K_SCROLL_UP",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Scroll Up",
    "page": "key",
    "shifted": false,
    "usage": 458997
  },
  {
    "name": "K_SCROLL_DOWN",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Scroll Down",
    "page": "key",
    "shifted": false,
    "usage": 458998
  },
  {
    "name": "K_EDIT",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Edit",
    "page": "key",
    "shifted": false,
    "usage": 458999
  },
  {
    "name": "K_SLEEP",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Sleep",
    "page": "key",
    "shifted": false,
    "usage": 459000
  },
  {
    "name": "K_LOCK",
    "aliases": [
      "K_SCREENSAVER",
      "K_COFFEE"
    ],
    "deprecated": [],
    "description": "Keyboard Lock",
    "page": "key",
    "shifted": false,
    "usage": 459001
  },
  {
    "name": "K_REFRESH",
    "aliases": [],
    "deprecated": [],
    "description": "Keyboard Refresh",
    "page": "key",
    "shifted": false,
    "usage": 459002
  },
  {
    "name": "K_CALCULATOR",
    "aliases": [
      "K_CALC"
    ],
    "deprecated": [],
    "description": "Keyboard Calculator",
    "page": "key",
    "shifted": false,
    "usage": 459003
  },
  {
    "name": "C_POWER",
    "aliases": [
      "C_PWR"
    ],
    "deprecated": [],
    "description": "Consumer Power",
    "page": "consumer",
    "shifted": false,
    "usage": 786480
  },
  {
    "name": "C_RESET",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Reset",
    "page": "consumer",
    "shifted": false,
    "usage": 786481
  },
  {
    "name": "C_SLEEP",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Sleep",
    "page": "consumer",
    "shifted": false,
    "usage": 786482
  },
  {
    "name": "C_SLEEP_MODE",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Sleep Mode",
    "page": "consumer",
    "shifted": false,
    "usage": 786484
  },
  {
    "name": "C_MENU",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Menu",
    "page": "consumer",
    "shifted": false,
    "usage": 786496
  },
  {
    "name": "C_MENU_PICK",
    "aliases": [
      "C_MENU_SELECT"
    ],
    "deprecated": [],
    "description": "Consumer Menu Pick",
    "page": "consumer",
    "shifted": false,
    "usage": 786497
  },
  {
    "name": "C_MENU_UP",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Menu Up",
    "page": "consumer",
    "shifted": false,
    "usage": 786498
  },
  {
    "name": "C_MENU_DOWN",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Menu Down",
    "page": "consumer",
    "shifted": false,
    "usage": 786499
  },
  {
    "name": "C_MENU_LEFT",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Menu Left",
    "page": "consumer",
    "shifted": false,
    "usage": 786500
  },
  {
    "name": "C_MENU_RIGHT",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Menu Right",
    "page": "consumer",
    "shifted": false,
    "usage": 786501
  },
  {
    "name": "C_MENU_ESCAPE",
    "aliases": [
      "C_MENU_ESC"
    ],
    "deprecated": [],
    "description": "Consumer Menu Escape",
    "page": "consumer",
    "shifted": false,
    "usage": 786502
  },
  {
    "name": "C_MENU_INCREASE",
    "aliases": [
      "C_MENU_INC"
    ],
    "deprecated": [],
    "description": "Consumer Menu Value Increase",
    "page": "consumer",
    "shifted": false,
    "usage": 786503
  },
  {
    "name": "C_MENU_DECREASE",
    "aliases": [
      "C_MENU_DEC"
    ],
    "deprecated": [],
    "description": "Consumer Menu Value Decrease",
    "page": "consumer",
    "shifted": false,
    "usage": 786504
  },
  {
    "name": "C_DATA_ON_SCREEN",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Data On Screen",
    "page": "consumer",
    "shifted": false,
    "usage": 786528
  },
  {
    "name": "C_CAPTIONS",
    "aliases": [
      "C_SUBTITLES"
    ],
    "deprecated": [],
    "description": "Consumer Closed Caption",
    "page": "consumer",
    "shifted": false,
    "usage": 786529
  },
  {
    "name": "C_SNAPSHOT",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Snapshot",
    "page": "consumer",
    "shifted": false,
    "usage": 786533
  },
  {
    "name": "C_PIP",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Picture-in-Picture Toggle",
    "page": "consumer",
    "shifted": false,
    "usage": 786535
  },
  {
    "name": "C_RED_BUTTON",
    "aliases": [
      "C_RED"
    ],
    "deprecated": [],
    "description": "Consumer Red Menu Button",
    "page": "consumer",
    "shifted": false,
    "usage": 786537
  },
  {
    "name": "C_GREEN_BUTTON",
    "aliases": [
      "C_GREEN"
    ],
    "deprecated": [],
    "description": "Consumer Green Menu Button",
    "page": "consumer",
    "shifted": false,
    "usage": 786538
  },
  {
    "name": "C_BLUE_BUTTON",
    "aliases": [
      "C_BLUE"
    ],
    "deprecated": [],
    "description": "Consumer Blue Menu Button",
    "page": "consumer",
    "shifted": false,
    "usage": 786539
  },
  {
    "name": "C_YELLOW_BUTTON",
    "aliases": [
      "C_YELLOW"
    ],
    "deprecated": [],
    "description": "Consumer Yellow Menu Button",
    "page": "consumer",
    "shifted": false,
    "usage": 786540
  },
  {
    "name": "C_ASPECT",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Aspect",
    "page": "consumer",
    "shifted": false,
    "usage": 786541
  },
  {
    "name": "C_BRIGHTNESS_INC",
    "aliases": [
      "C_BRI_INC",
      "C_BRI_UP"
    ],
    "deprecated": [],
    "description": "Consumer Display Brightness Increment",
    "page": "consumer",
    "shifted": false,
    "usage": 786543
  },
  {
    "name": "C_BRIGHTNESS_DEC",
    "aliases": [
      "C_BRI_DEC",
      "C_BRI_DN"
    ],
    "deprecated": [],
    "description": "Consumer Display Brightness Decrement",
    "page": "consumer",
    "shifted": false,
    "usage": 786544
  },
  {
    "name": "C_BACKLIGHT_TOGGLE",
    "aliases": [
      "C_BKLT_TOG"
    ],
    "deprecated": [],
    "description": "Consumer Display Backlight Toggle",
    "page": "consumer",
    "shifted": false,
    "usage": 786546
  },
  {
    "name": "C_BRIGHTNESS_MINIMUM",
    "aliases": [
      "C_BRI_MIN"
    ],
    "deprecated": [],
    "description": "Consumer Display Set Brightness to Minimum",
    "page": "consumer",
    "shifted": false,
    "usage": 786547
  },
  {
    "name": "C_BRIGHTNESS_MAXIMUM",
    "aliases": [
      "C_BRI_MAX"
    ],
    "deprecated": [],
    "description": "Consumer Display Set Brightness to Maximum",
    "page": "consumer",
    "shifted": false,
    "usage": 786548
  },
  {
    "name": "C_BRIGHTNESS_AUTO",
    "aliases": [
      "C_BRI_AUTO"
    ],
    "deprecated": [],
    "description": "Consumer Display Set Auto Brightness",
    "page": "consumer",
    "shifted": false,
    "usage": 786549
  },
  {
    "name": "C_MEDIA_STEP",
    "aliases": [
      "C_MODE_STEP"
    ],
    "deprecated": [],
    "description": "Consumer Mode Step",
    "page": "consumer",
    "shifted": false,
    "usage": 786562
  },
  {
    "name": "C_RECALL_LAST",
    "aliases": [
      "C_CHAN_LAST"
    ],
    "deprecated": [],
    "description": "Consumer Recall Last",
    "page": "consumer",
    "shifted": false,
    "usage": 786563
  },
  {
    "name": "C_MEDIA_COMPUTER",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Media Select Computer",
    "page": "consumer",
    "shifted": false,
    "usage": 786568
  },
  {
    "name": "C_MEDIA_TV",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Media Select TV",
    "page": "consumer",
    "shifted": false,
    "usage": 786569
  },
  {
    "name": "C_MEDIA_WWW",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Media Select WWW",
    "page": "consumer",
    "shifted": false,
    "usage": 786570
  },
  {
    "name": "C_MEDIA_DVD",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Media Select DVD",
    "page": "consumer",
    "shifted": false,
    "usage": 786571
  },
  {
    "name": "C_MEDIA_PHONE",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Media Select Telephone",
    "page": "consumer",
    "shifted": false,
    "usage": 786572
  },
  {
    "name": "C_MEDIA_GUIDE",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Media Select Program Guide",
    "page": "consumer",
    "shifted": false,
    "usage": 786573
  },
  {
    "name": "C_MEDIA_VIDEOPHONE",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Media Select Video Phone",
    "page": "consumer",
    "shifted": false,
    "usage": 786574
  },
  {
    "name": "C_MEDIA_GAMES",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Media Select Games",
    "page": "consumer",
    "shifted": false,
    "usage": 786575
  },
  {
    "name": "C_MEDIA_MESSAGES",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Media Select Messages",
    "page": "consumer",
    "shifted": false,
    "usage": 786576
  },
  {
    "name": "C_MEDIA_CD",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Media Select CD",
    "page": "consumer",
    "shifted": false,
    "usage": 786577
  },
  {
    "name": "C_MEDIA_VCR",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Media Select VCR",
    "page": "consumer",
    "shifted": false,
    "usage": 786578
  },
  {
    "name": "C_MEDIA_TUNER",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Media Select Tuner",
    "page": "consumer",
    "shifted": false,
    "usage": 786579
  },
  {
    "name": "C_QUIT",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Quit",
    "page": "consumer",
    "shifted": false,
    "usage": 786580
  },
  {
    "name": "C_HELP",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Help",
    "page": "consumer",
    "shifted": false,
    "usage": 786581
  },
  {
    "name": "C_MEDIA_TAPE",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Media Select Tape",
    "page": "consumer",
    "shifted": false,
    "usage": 786582
  },
  {
    "name": "C_MEDIA_CABLE",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Media Select Cable",
    "page": "consumer",
    "shifted": false,
    "usage": 786583
  },
  {
    "name": "C_MEDIA_SATELLITE",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Media Select Satellite",
    "page": "consumer",
    "shifted": false,
    "usage": 786584
  },
  {
    "name": "C_MEDIA_HOME",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Media Select Home",
    "page": "consumer",
    "shifted": false,
    "usage": 786586
  },
  {
    "name": "C_CHANNEL_INC",
    "aliases": [
      "C_CHAN_INC"
    ],
    "deprecated": [],
    "description": "Consumer Channel Increment",
    "page": "consumer",
    "shifted": false,
    "usage": 786588
  },
  {
    "name": "C_CHANNEL_DEC",
    "aliases": [
      "C_CHAN_DEC"
    ],
    "deprecated": [],
    "description": "Consumer Channel Decrement",
    "page": "consumer",
    "shifted": false,
    "usage": 786589
  },
  {
    "name": "C_MEDIA_VCR_PLUS",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer VCR Plus",
    "page": "consumer",
    "shifted": false,
    "usage": 786592
  },
  {
    "name": "C_PLAY",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Play",
    "page": "consumer",
    "shifted": false,
    "usage": 786608
  },
  {
    "name": "C_PAUSE",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Pause",
    "page": "consumer",
    "shifted": false,
    "usage": 786609
  },
  {
    "name": "C_RECORD",
    "aliases": [
      "C_REC"
    ],
    "deprecated": [],
    "description": "Consumer Record",
    "page": "consumer",
    "shifted": false,
    "usage": 786610
  },
  {
    "name": "C_FAST_FORWARD",
    "aliases": [
      "C_FF"
    ],
    "deprecated": [],
    "description": "Consumer Fast Forward",
    "page": "consumer",
    "shifted": false,
    "usage": 786611
  },
  {
    "name": "C_REWIND",
    "aliases": [
      "C_RW"
    ],
    "deprecated": [],
    "description": "Consumer Rewind",
    "page": "consumer",
    "shifted": false,
    "usage": 786612
  },
  {
    "name": "C_NEXT",
    "aliases": [],
    "deprecated": [
      "M_NEXT"
    ],
    "description": "Consumer Scan Next Track",
    "page": "consumer",
    "shifted": false,
    "usage": 786613
  },
  {
    "name": "C_PREVIOUS",
    "aliases": [
      "C_PREV"
    ],
    "deprecated": [
      "M_PREV"
    ],
    "description": "Consumer Scan Previous Track",
    "page": "consumer",
    "shifted": false,
    "usage": 786614
  },
  {
    "name": "C_STOP",
    "aliases": [],
    "deprecated": [
      "M_STOP"
    ],
    "description": "Consumer Stop",
    "page": "consumer",
    "shifted": false,
    "usage": 786615
  },
  {
    "name": "C_EJECT",
    "aliases": [],
    "deprecated": [
      "M_EJCT"
    ],
    "description": "Consumer Eject",
    "page": "consumer",
    "shifted": false,
    "usage": 786616
  },
  {
    "name": "C_RANDOM_PLAY",
    "aliases": [
      "C_SHUFFLE"
    ],
    "deprecated": [],
    "description": "Consumer Random Play",
    "page": "consumer",
    "shifted": false,
    "usage": 786617
  },
  {
    "name": "C_REPEAT",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Repeat",
    "page": "consumer",
    "shifted": false,
    "usage": 786620
  },
  {
    "name": "C_SLOW_TRACKING",
    "aliases": [
      "C_SLOW2"
    ],
    "deprecated": [],
    "description": "Consumer Slow Tracking",
    "page": "consumer",
    "shifted": false,
    "usage": 786623
  },
  {
    "name": "C_STOP_EJECT",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Stop/Eject",
    "page": "consumer",
    "shifted": false,
    "usage": 786636
  },
  {
    "name": "C_PLAY_PAUSE",
    "aliases": [
      "C_PP"
    ],
    "deprecated": [
      "M_PLAY"
    ],
    "description": "Consumer Play/Pause",
    "page": "consumer",
    "shifted": false,
    "usage": 786637
  },
  {
    "name": "C_VOICE_COMMAND",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Voice Command",
    "page": "consumer",
    "shifted": false,
    "usage": 786639
  },
  {
    "name": "C_MUTE",
    "aliases": [],
    "deprecated": [
      "M_MUTE"
    ],
    "description": "Consumer Mute",
    "page": "consumer",
    "shifted": false,
    "usage": 786658
  },
  {
    "name": "C_BASS_BOOST",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Bass Boost",
    "page": "consumer",
    "shifted": false,
    "usage": 786661
  },
  {
    "name": "C_VOLUME_UP",
    "aliases": [
      "C_VOL_UP"
    ],
    "deprecated": [
      "M_VOLU"
    ],
    "description": "Consumer Volume Increment",
    "page": "consumer",
    "shifted": false,
    "usage": 786665
  },
  {
    "name": "C_VOLUME_DOWN",
    "aliases": [
      "C_VOL_DN"
    ],
    "deprecated": [
      "M_VOLD"
    ],
    "description": "Consumer Volume Decrement",
    "page": "consumer",
    "shifted": false,
    "usage": 786666
  },
  {
    "name": "C_SLOW",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer Slow",
    "page": "consumer",
    "shifted": false,
    "usage": 786677
  },
  {
    "name": "C_ALTERNATE_AUDIO_INCREMENT",
    "aliases": [
      "C_ALT_AUDIO_INC"
    ],
    "deprecated": [],
    "description": "Consumer Alternate Audio Increment",
    "page": "consumer",
    "shifted": false,
    "usage": 786803
  },
  {
    "name": "C_AL_CCC",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Consumer Control Configuration",
    "page": "consumer",
    "shifted": false,
    "usage": 786819
  },
  {
    "name": "C_AL_WORD",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Word Processor",
    "page": "consumer",
    "shifted": false,
    "usage": 786820
  },
  {
    "name": "C_AL_TEXT_EDITOR",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Text Editor",
    "page": "consumer",
    "shifted": false,
    "usage": 786821
  },
  {
    "name": "C_AL_SPREADSHEET",
    "aliases": [
      "C_AL_SHEET"
    ],
    "deprecated": [],
    "description": "Consumer AL Spreadsheet",
    "page": "consumer",
    "shifted": false,
    "usage": 786822
  },
  {
    "name": "C_AL_GRAPHICS_EDITOR",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Graphics Editor",
    "page": "consumer",
    "shifted": false,
    "usage": 786823
  },
  {
    "name": "C_AL_PRESENTATION",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Presentation App",
    "page": "consumer",
    "shifted": false,
    "usage": 786824
  },
  {
    "name": "C_AL_DATABASE",
    "aliases": [
      "C_AL_DB"
    ],
    "deprecated": [],
    "description": "Consumer AL Database App",
    "page": "consumer",
    "shifted": false,
    "usage": 786825
  },
  {
    "name": "C_AL_EMAIL",
    "aliases": [
      "C_AL_MAIL"
    ],
    "deprecated": [],
    "description": "Consumer AL Email Reader",
    "page": "consumer",
    "shifted": false,
    "usage": 786826
  },
  {
    "name": "C_AL_NEWS",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Newsreader",
    "page": "consumer",
    "shifted": false,
    "usage": 786827
  },
  {
    "name": "C_AL_VOICEMAIL",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Voicemail",
    "page": "consumer",
    "shifted": false,
    "usage": 786828
  },
  {
    "name": "C_AL_CONTACTS",
    "aliases": [
      "C_AL_ADDRESS_BOOK"
    ],
    "deprecated": [],
    "description": "Consumer AL Contacts/Address Book",
    "page": "consumer",
    "shifted": false,
    "usage": 786829
  },
  {
    "name": "C_AL_CALENDAR",
    "aliases": [
      "C_AL_CAL"
    ],
    "deprecated": [],
    "description": "Consumer AL Calendar/Schedule",
    "page": "consumer",
    "shifted": false,
    "usage": 786830
  },
  {
    "name": "C_AL_TASK_MANAGER",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Task/Project Manager",
    "page": "consumer",
    "shifted": false,
    "usage": 786831
  },
  {
    "name": "C_AL_JOURNAL",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Log/Journal/Timecard",
    "page": "consumer",
    "shifted": false,
    "usage": 786832
  },
  {
    "name": "C_AL_FINANCE",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Checkbook/Finance",
    "page": "consumer",
    "shifted": false,
    "usage": 786833
  },
  {
    "name": "C_AL_CALCULATOR",
    "aliases": [
      "C_AL_CALC"
    ],
    "deprecated": [],
    "description": "Consumer AL Calculator",
    "page": "consumer",
    "shifted": false,
    "usage": 786834
  },
  {
    "name": "C_AL_AV_CAPTURE_PLAYBACK",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL A/V Capture/Playback",
    "page": "consumer",
    "shifted": false,
    "usage": 786835
  },
  {
    "name": "C_AL_MY_COMPUTER",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Local Machine Browser",
    "page": "consumer",
    "shifted": false,
    "usage": 786836
  },
  {
    "name": "C_AL_WWW",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Internet Browser",
    "page": "consumer",
    "shifted": false,
    "usage": 786838
  },
  {
    "name": "C_AL_NETWORK_CHAT",
    "aliases": [
      "C_AL_CHAT"
    ],
    "deprecated": [],
    "description": "Consumer AL Network Chat",
    "page": "consumer",
    "shifted": false,
    "usage": 786841
  },
  {
    "name": "C_AL_LOGOFF",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Logoff",
    "page": "consumer",
    "shifted": false,
    "usage": 786844
  },
  {
    "name": "C_AL_LOCK",
    "aliases": [
      "C_AL_SCREENSAVER",
      "C_AL_COFFEE"
    ],
    "deprecated": [],
    "description": "Consumer AL Terminal Lock/Screensaver",
    "page": "consumer",
    "shifted": false,
    "usage": 786846
  },
  {
    "name": "C_AL_CONTROL_PANEL",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Control Panel",
    "page": "consumer",
    "shifted": false,
    "usage": 786847
  },
  {
    "name": "C_AL_SELECT_TASK",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Select Task/Application",
    "page": "consumer",
    "shifted": false,
    "usage": 786850
  },
  {
    "name": "C_AL_NEXT_TASK",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Next Task/Application",
    "page": "consumer",
    "shifted": false,
    "usage": 786851
  },
  {
    "name": "C_AL_PREVIOUS_TASK",
    "aliases": [
      "C_AL_PREV_TASK"
    ],
    "deprecated": [],
    "description": "Consumer AL Previous Task/Application",
    "page": "consumer",
    "shifted": false,
    "usage": 786852
  },
  {
    "name": "C_AL_HELP",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Integrated Help Center",
    "page": "consumer",
    "shifted": false,
    "usage": 786854
  },
  {
    "name": "C_AL_DOCUMENTS",
    "aliases": [
      "C_AL_DOCS"
    ],
    "deprecated": [],
    "description": "Consumer AL Documents",
    "page": "consumer",
    "shifted": false,
    "usage": 786855
  },
  {
    "name": "C_AL_SPELLCHECK",
    "aliases": [
      "C_AL_SPELL"
    ],
    "deprecated": [],
    "description": "Consumer AL Spell Check",
    "page": "consumer",
    "shifted": false,
    "usage": 786859
  },
  {
    "name": "C_AL_KEYBOARD_LAYOUT",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Keyboard Layout",
    "page": "consumer",
    "shifted": false,
    "usage": 786862
  },
  {
    "name": "C_AL_SCREEN_SAVER",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AL Screen Saver",
    "page": "consumer",
    "shifted": false,
    "usage": 786865
  },
  {
    "name": "C_AL_FILE_BROWSER",
    "aliases": [
      "C_AL_FILES"
    ],
    "deprecated": [],
    "description": "Consumer AL File Browser",
    "page": "consumer",
    "shifted": false,
    "usage": 786868
  },
  {
    "name": "C_AL_IMAGE_BROWSER",
    "aliases": [
      "C_AL_IMAGES"
    ],
    "deprecated": [],
    "description": "Consumer AL Image Browser",
    "page": "consumer",
    "shifted": false,
    "usage": 786870
  },
  {
    "name": "C_AL_AUDIO_BROWSER",
    "aliases": [
      "C_AL_AUDIO",
      "C_AL_MUSIC"
    ],
    "deprecated": [],
    "description": "Consumer AL Audio Browser",
    "page": "consumer",
    "shifted": false,
    "usage": 786871
  },
  {
    "name": "C_AL_MOVIE_BROWSER",
    "aliases": [
      "C_AL_MOVIES"
    ],
    "deprecated": [],
    "description": "Consumer AL Movie Browser",
    "page": "consumer",
    "shifted": false,
    "usage": 786872
  },
  {
    "name": "C_AL_INSTANT_MESSAGING",
    "aliases": [
      "C_AL_IM"
    ],
    "deprecated": [],
    "description": "Consumer AL Instant Messaging",
    "page": "consumer",
    "shifted": false,
    "usage": 786876
  },
  {
    "name": "C_AL_OEM_FEATURES",
    "aliases": [
      "C_AL_TIPS",
      "C_AL_TUTORIAL"
    ],
    "deprecated": [],
    "description": "Consumer AL OEM Features/Tips/Tutorial Browser",
    "page": "consumer",
    "shifted": false,
    "usage": 786877
  },
  {
    "name": "C_AC_NEW",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC New",
    "page": "consumer",
    "shifted": false,
    "usage": 786945
  },
  {
    "name": "C_AC_OPEN",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Open",
    "page": "consumer",
    "shifted": false,
    "usage": 786946
  },
  {
    "name": "C_AC_CLOSE",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Close",
    "page": "consumer",
    "shifted": false,
    "usage": 786947
  },
  {
    "name": "C_AC_EXIT",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Exit",
    "page": "consumer",
    "shifted": false,
    "usage": 786948
  },
  {
    "name": "C_AC_SAVE",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Save",
    "page": "consumer",
    "shifted": false,
    "usage": 786951
  },
  {
    "name": "C_AC_PRINT",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Print",
    "page": "consumer",
    "shifted": false,
    "usage": 786952
  },
  {
    "name": "C_AC_PROPERTIES",
    "aliases": [
      "C_AC_PROPS"
    ],
    "deprecated": [],
    "description": "Consumer AC Properties",
    "page": "consumer",
    "shifted": false,
    "usage": 786953
  },
  {
    "name": "C_AC_UNDO",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Undo",
    "page": "consumer",
    "shifted": false,
    "usage": 786970
  },
  {
    "name": "C_AC_COPY",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Copy",
    "page": "consumer",
    "shifted": false,
    "usage": 786971
  },
  {
    "name": "C_AC_CUT",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Cut",
    "page": "consumer",
    "shifted": false,
    "usage": 786972
  },
  {
    "name": "C_AC_PASTE",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Paste",
    "page": "consumer",
    "shifted": false,
    "usage": 786973
  },
  {
    "name": "C_AC_FIND",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Find",
    "page": "consumer",
    "shifted": false,
    "usage": 786975
  },
  {
    "name": "C_AC_SEARCH",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Search",
    "page": "consumer",
    "shifted": false,
    "usage": 786977
  },
  {
    "name": "C_AC_GOTO",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Go To",
    "page": "consumer",
    "shifted": false,
    "usage": 786978
  },
  {
    "name": "C_AC_HOME",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Home",
    "page": "consumer",
    "shifted": false,
    "usage": 786979
  },
  {
    "name": "C_AC_BACK",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Back",
    "page": "consumer",
    "shifted": false,
    "usage": 786980
  },
  {
    "name": "C_AC_FORWARD",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Forward",
    "page": "consumer",
    "shifted": false,
    "usage": 786981
  },
  {
    "name": "C_AC_STOP",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Stop",
    "page": "consumer",
    "shifted": false,
    "usage": 786982
  },
  {
    "name": "C_AC_REFRESH",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Refresh",
    "page": "consumer",
    "shifted": false,
    "usage": 786983
  },
  {
    "name": "C_AC_BOOKMARKS",
    "aliases": [
      "C_AC_FAVORITES",
      "C_AC_FAVOURITES"
    ],
    "deprecated": [],
    "description": "Consumer AC Bookmarks",
    "page": "consumer",
    "shifted": false,
    "usage": 786986
  },
  {
    "name": "C_AC_ZOOM_IN",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Zoom In",
    "page": "consumer",
    "shifted": false,
    "usage": 786989
  },
  {
    "name": "C_AC_ZOOM_OUT",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Zoom Out",
    "page": "consumer",
    "shifted": false,
    "usage": 786990
  },
  {
    "name": "C_AC_ZOOM",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Zoom",
    "page": "consumer",
    "shifted": false,
    "usage": 786991
  },
  {
    "name": "C_AC_VIEW_TOGGLE",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC View Toggle",
    "page": "consumer",
    "shifted": false,
    "usage": 786994
  },
  {
    "name": "C_AC_SCROLL_UP",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Scroll Up",
    "page": "consumer",
    "shifted": false,
    "usage": 786995
  },
  {
    "name": "C_AC_SCROLL_DOWN",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Scroll Down",
    "page": "consumer",
    "shifted": false,
    "usage": 786996
  },
  {
    "name": "C_AC_EDIT",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Edit",
    "page": "consumer",
    "shifted": false,
    "usage": 787005
  },
  {
    "name": "C_AC_CANCEL",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Cancel",
    "page": "consumer",
    "shifted": false,
    "usage": 787039
  },
  {
    "name": "C_AC_INSERT",
    "aliases": [
      "C_AC_INS"
    ],
    "deprecated": [],
    "description": "Consumer AC Insert Mode",
    "page": "consumer",
    "shifted": false,
    "usage": 787049
  },
  {
    "name": "C_AC_DEL",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Delete",
    "page": "consumer",
    "shifted": false,
    "usage": 787050
  },
  {
    "name": "C_AC_REDO",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Redo/Repeat",
    "page": "consumer",
    "shifted": false,
    "usage": 787065
  },
  {
    "name": "C_AC_REPLY",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Reply",
    "page": "consumer",
    "shifted": false,
    "usage": 787081
  },
  {
    "name": "C_AC_FORWARD_MAIL",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Forward Msg",
    "page": "consumer",
    "shifted": false,
    "usage": 787083
  },
  {
    "name": "C_AC_SEND",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Send",
    "page": "consumer",
    "shifted": false,
    "usage": 787084
  },
  {
    "name": "C_AC_DESKTOP_SHOW_ALL_WINDOWS",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Desktop Show All Windows",
    "page": "consumer",
    "shifted": false,
    "usage": 787103
  },
  {
    "name": "C_AC_DESKTOP_SHOW_ALL_APPLICATIONS",
    "aliases": [],
    "deprecated": [],
    "description": "Consumer AC Desktop Show All Applications",
    "page": "consumer",
    "shifted": false,
    "usage": 787106
  },
  {
    "name": "C_KEYBOARD_INPUT_ASSIST_PREVIOUS",
    "aliases": [
      "C_KBIA_PREV"
    ],
    "deprecated": [],
    "description": "Consumer Keyboard Input Assist Previous",
    "page": "consumer",
    "shifted": false,
    "usage": 787143
  },
  {
    "name": "C_KEYBOARD_INPUT_ASSIST_NEXT",
    "aliases": [
      "C_KBIA_NEXT"
    ],
    "deprecated": [],
    "description": "Consumer Keyboard Input Assist Next",
    "page": "consumer",
    "shifted": false,
    "usage": 787144
  },
  {
    "name": "C_KEYBOARD_INPUT_ASSIST_PREVIOUS_GROUP",
    "aliases": [
      "C_KBIA_PREV_GRP"
    ],
    "deprecated": [],
    "description": "Consumer Keyboard Input Assist Previous Group",
    "page": "consumer",
    "shifted": false,
    "usage": 787145
  },
  {
    "name": "C_KEYBOARD_INPUT_ASSIST_NEXT_GROUP",
    "aliases": [
      "C_KBIA_NEXT_GRP"
    ],
    "deprecated": [],
    "description": "Consumer Keyboard Input Assist Next Group",
    "page": "consumer",
    "shifted": false,
    "usage": 787146
  },
  {
    "name": "C_KEYBOARD_INPUT_ASSIST_ACCEPT",
    "aliases": [
      "C_KBIA_ACCEPT"
    ],
    "deprecated": [],
    "description": "Consumer Keyboard Input Assist Accept",
    "page": "consumer",
    "shifted": false,
    "usage": 787147
  },
  {
    "name": "C_KEYBOARD_INPUT_ASSIST_CANCEL",
    "aliases": [
      "C_KBIA_CANCEL"
    ],
    "deprecated": [],
    "description": "Consumer Keyboard Input Assist Cancel",
    "page": "consumer",
    "shifted": false,
    "usage": 787148
  },
  {
    "name": "C_AC_NEXT_KEYBOARD_LAYOUT_SELECT",
    "aliases": [
      "GLOBE"
    ],
    "deprecated": [],
    "description": "Apple Globe key",
    "page": "consumer",
    "shifted": false,
    "usage": 787101
  }
];
