// Generates src/core/catalog/unicode.data.ts from zmk-unicode's language alias headers.
// Usage: node scripts/gen-unicode.mjs [ref]   (default ref: v0.3)
import { writeFileSync } from 'node:fs';

const ref = process.argv[2] ?? 'v0.3';
const base = `https://raw.githubusercontent.com/urob/zmk-unicode/${ref}/include/zmk-unicode`;

async function get(path) {
  const response = await fetch(`${base}/${path}`);
  if (!response.ok) throw new Error(`${path}: ${response.status}`);
  return response.text();
}

const index = await get('keys.h');
const languages = [...index.matchAll(/#include <zmk-unicode\/keys\/(\w+)\.h>/g)].map((m) => m[1]);

const aliases = [];
for (const language of languages) {
  const header = await get(`keys/${language}.h`);
  for (const match of header.matchAll(/^#define\s+(UC_\w+)\s+(0x[0-9a-fA-F]+)\s+(0x[0-9a-fA-F]+)/gm)) {
    const [, name, lower, upper] = match;
    aliases.push({ name, language, lower: Number(lower), upper: Number(upper) });
  }
}

const out = `// Generated by scripts/gen-unicode.mjs from zmk-unicode ${ref}. Do not edit.

export interface UnicodeAliasData {
  /** Macro name, e.g. UC_SV_AE. */
  name: string;
  /** Header it comes from, e.g. swedish. */
  language: string;
  /** Code point without Shift. */
  lower: number;
  /** Code point with Shift. */
  upper: number;
}

export const UNICODE_ALIASES: UnicodeAliasData[] = [
${aliases.map((a) => `  { name: '${a.name}', language: '${a.language}', lower: 0x${a.lower.toString(16)}, upper: 0x${a.upper.toString(16)} },`).join('\n')}
];
`;
writeFileSync(new URL('../src/core/catalog/unicode.data.ts', import.meta.url), out);
console.log(`Wrote ${aliases.length} aliases from ${languages.length} languages`);
